### ISSUE TITLE
Customize Isolate Tool

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#1000]

**Comment by htlcnn** [comment]
@eirannejad could you give a brief description of the tool so that I (or someone) can help implement it?

**Comment by eirannejad** [comment]
We need to modify the isolate tool so it has a customizable list of options. Like the how the updated Pick tool works (Shift +Click has the list of all categories that could be customized)

**Comment by htlcnn** [comment]
@eirannejad Should they be the same options for Pick and Isolate button? Or should they be saved by different config name?

**Comment by eirannejad** [comment]
I think it could be the same. They'd both need a category selector options I guess

**Comment by htlcnn** [comment]
But for Isolate button, I see additional options that are not categories: Model Elements, Painted Elements. I think they should be separated. It's also easier to code because they're saved as configs for different buttons. If you want to use 1 config for both buttons, we have to agree on 1 config section name such as `frequently_used_categories`

**Comment by eirannejad** [comment]
Maybe we keep those as fixed and only have the categories configurable?

**Comment by htlcnn** [comment]
@eirannejad I made a PR: https://github.com/eirannejad/pyRevit/pull/1058 and made some behaviour change. Please have a look. 
Most of the config code was taken from yours :)
Thanks!

**Comment by eirannejad** [comment]
I'll publish your changes very soon (by next Sunday I hope) - Waiting for another changes to be completed as well. Thank you soooo much
