### ISSUE TITLE
Load all families from folder tree

### ISSUE THREAD

**Issue by DuncanLithgow** [eirannejad/pyRevit#1015]
**Is your feature request related to a problem? Please describe.**
When testing families that would normally be in a content management system it's useful to be able to load many families at once. A tools for this would be great.

**Describe the solution you'd like**
There is a 'Load more types' Family tools. I'd love a 'load more families' tool which accepts a folder as input and then asks if all families should be loaded recursively. Trying to filter backups out would of course be a good idea, other wise a warning is fine.

**Describe alternatives you've considered**
Loading them one at a time ... boring

**Additional context**
Suggestions:
Name: Load Multiple Families
Description: Loads multiple Families from a folder structure, while trying to avoid backups
Options: yes/no: load recursively. Radio buttons: load only family or load all types from Type Catalogue

An extension of functionality would be a dialogue like the purge dialogue which allows for selecting individual types to be loaded.

**Comment by hikmet-kibar** [comment]
@DuncanLithgow 
Liked the idea, made the tool -> [LoadFamilies.pushbutton](https://github.com/hikmet-kibar/LoadFamilies.pushbutton)
Since I don´t have a large set of tools, I did not create a whole extension. You can [create you own extension ](https://www.notion.so/Create-Your-First-Command-2509b43e28bd498fba937f5c1be7f485), if you don´t already have a custom one, and add this tool.
I could only test it for myself - Let me know how it goes for you.

@eirannejad 
Many parts are based on your `Load More Types` tool. Credit can be found in the docstrings of the classes.

**Comment by eirannejad** [comment]
@hikmet-kibar This is great. I'll grab it from your repo and will add to the toolbar

**Comment by david939david** [comment]
@hikmet-kibar Thank you for the link to "create your first command", it helped me a lot with understanding what is going on ;)
