### ISSUE TITLE
outputstyles.css not binded to pyRevit GUI settings in the develop branch

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#1122]
**Describe the bug**

![image](https://user-images.githubusercontent.com/7872003/104427612-bb840400-5583-11eb-8cde-e49fefe61942.png)

**To Reproduce**

1. attach the develop branch 
2. use preflight
3. no md or html styling

**Expected behavior**
this field is empty but when pointing to the right file:
![image](https://user-images.githubusercontent.com/7872003/104427626-c0e14e80-5583-11eb-9f6f-22f6f99215e0.png)

**Desktop (please complete the following information):**

 - pyRevit develop branch

**Comment by jmcouffin** [comment]
That happens with a clean install with the `pyRevit Clone` command

**Comment by jmcouffin** [comment]
The reset button fixed it on another computer install

**Comment by eirannejad** [comment]
@jmcouffin Are you switching branches in the same repo to `develop` or creating complete new clones? The path will be cleared out if pyRevit settings can not find the `.css` file. Based on the path you shared, it seems like you have a complete separate clone to work on `preflight` right?

**Comment by jmcouffin** [comment]
I had to create a new clone in the end. so yes

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by chttIE** [comment]
Hi, I can somehow replace the path to outputstyles.css ?
I want the path to outputstyles.css to be different when uploading HTML. 
The idea is to place the style in a common repository, so that people who do not have pyrevit installed, but working in the company HTML displayed correctly.
![image](https://github.com/eirannejad/pyRevit/assets/128715491/04a8002d-3be1-4694-9839-67993ef3e6ab)
