### ISSUE TITLE
Unable to change Iron Python version

### ISSUE THREAD

**Issue by Ambientnite** [eirannejad/pyRevit#1260]
**Issue:**
I used to use Iron Python 279 and updated to 4.8.7 a couple weeks ago to use pyRevit with 2022 and as of today I noticed that I'm unable to choose which Active Engine I'm using for Iron Python.  I have 273 and 277-2711R installed in my engines folder, but 277 is selected in the pyRevit settings inside Revit and I'm unable to change it, the dropdown is greyed out.  My first instinct was to update pyRevit, so I went here and downloaded and installed 4.8.8 and for some reason when I check the About after that it still says I'm running 4.8.7.  I've tried running the pyrevit doctor, I've tried uninstalling pyRevit, I've restarted my computer, and no luck with changing anything.

**Screenshots:**
I attached a screenshot with the greyed out Active Engine and the About window.
![IronPython Version](https://user-images.githubusercontent.com/85195472/120383063-019af380-c2ea-11eb-9edb-29d7eee99633.png)
![pyRevit About](https://user-images.githubusercontent.com/85195472/120383156-23947600-c2ea-11eb-9bc9-271f1a507016.PNG)

**Desktop:**
 - OS: Windows 10
 - pyRevit Version 4.8.7?
 - pyRevit Environment:

```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.8" | Path: "C:\Users\XXXXX\AppData\Roaming\pyRevit-Master"
==> Attachments
Unnamed-363FBF8 | Product: "2022 First Customer Ship" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "2021.1.3" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "2020.2.4" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
Unnamed-363FBF8 | Product: "2019.2.3" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
pyApex | Type: UIExtension | Repo: "XXXXX.git" | Installed: "XXXXX"
==> Default Extension Search Path
C:\Users\XXXXX\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
XXXXX
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2022 First Customer Ship | Version: 22.0.2.392 | Build: 20210224_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.3 | Version: 21.1.30.74 | Build: 20210426_1515(x64) | Language: 1033 | Path: "Revit 2021\"
2020.2.4 | Version: 20.2.40.65 | Build: 20210420_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 39288 | 2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.19042]
Executing User: XXXXX
Active User: XXXXX
Admin Access: No
%APPDATA%: "C:\Users\XXXXX\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 4.8.8.0```

**Comment by Ambientnite** [comment]
I reinstalled 4.8.8 and got it to show up in my About Tab correctly, but the Engine is still unable to be swapped, and if I look within the pyrevit-master folder I can see all the engines installed.
![image](https://user-images.githubusercontent.com/85195472/121241491-20a50280-c861-11eb-843b-7ea50bc95871.png)

**Comment by JBloss1517** [comment]
It is a file permissions error. Since you installed pyRevit as an admin (pyRevit-Master being located in the "C:/Program Files" directory not the "AppData/Roaming folder") the settings window is running into the `if attachment.IsReadOnly():` block and setting the combo box for the Ironpython engines enabled property as False. One way to check this is by commenting out the 'if' block and seeing if you can at least see the list of drop down engines available.

Since I'm not totally sure what needs to have both read and write access, you might uninstall pyrevit as admin and clear all traces of pyRevit on your Autodesk Revit Addins folder. You should be able to install it as a 'user' that has read and write access to all things pyRevit which will resolve the issue.

If you don't want to (or can't) uninstall as admin and run as 'user', @eirannejad do you know what folder @Ambientnite might need to gain read/write to? Is it the bin/engines folder?
![image](https://user-images.githubusercontent.com/50282451/125683510-f000eae9-2f5a-41b8-a5a5-c9deb49fb891.png)
