### ISSUE TITLE
Load Error: Process can not access config file

### ISSUE THREAD

**Issue by guy2201** [eirannejad/pyRevit#1280]
Hi

I'm not able to install pyrevit. please your help. i'm posting all the informatiom I can give:

1. installed pyRevit_4.8.8_signed.exe

2. opened revit 2020 and this error came up:
![image](https://user-images.githubusercontent.com/86149910/122638714-6c2b9c00-d0fe-11eb-81ce-8556b058e96c.png)

3. cmd as much as I can do:

![image](https://user-images.githubusercontent.com/86149910/122638733-86657a00-d0fe-11eb-99c0-8ef41061b9b2.png)

Thanks a lot for your kind help

Guy

**Comment by eirannejad** [comment]
Does this happen every time? As far as I know this only happens when multiple Revit instances are opening at the same time

**Comment by wangtie** [comment]
> 每次都这样吗？据我所知，这只发生在同时打开多个 Revit 实例时

yes,i have the same issue

**Comment by wangtie** [comment]
![image](https://user-images.githubusercontent.com/2143623/122719150-640b6200-d2a0-11eb-89b1-86bd8dcfd5ce.png)

**Comment by keldar67** [comment]
We have one user out of a group of circa 30 having this issue currently also.

This is happening in a single session of Revit, No other sessions running. It has been happening for a number of days now, and machine has been completely shut down and restarted each day.

Any suggestions appreciated
Thanks in advance

![pyRevitConfigFileError](https://user-images.githubusercontent.com/2543479/122866444-48b95900-d36b-11eb-89ce-85f4a34f43f5.png)

**Comment by Blame4** [comment]
revit2019 same issue

**Comment by Blame4** [comment]
Hei Guys! I have found a way out. 
1.Back up the original ini file in another folder.
2.delete ini file
3.replace the content in the newly generated file with the one in  the original file

I don't know how it works, the permission property is the same.

**Comment by anthonymcflare** [comment]
It works!

**Comment by legend-oe** [comment]
> Hei Guys! I have found a way out.

Thank you!
It's work. You save my time :)
Revit2021 / Windows7 - same issue.

**Comment by kendraanth** [comment]
I'm having this issue as well. No Revits will launch (2020-2022 all start to launch then close out eventually without an error notice)

**Comment by khogan26** [comment]
Hi,

Why is this closed and why is this the solution?  Can't we actually figure out the reason and fix it?

1.Back up the original ini file in another folder.
2.delete ini file
3.start revit
4.close revit
5.replace the content in the newly generated file with the one in the original file

I don't know why it works, the permission property is the same.

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists

**Comment by kollyboi** [comment]
Hi.
I vote for this issue to be re-opened.
I'm still struggling after the new installation files, pyRevit_4.8.9.21361+0320_signed.exe both for user installation and for admin installation.

For the User installation, the pyrevit.addin looks like this and is in ProgramData folder. This means every user on the machine loads pyrevitloader.dll from my user folder on Revit startup. 
![image](https://user-images.githubusercontent.com/44774905/148273659-74f32529-fd3e-46a2-aa9c-a4545adaa258.png)
Also, there are two pyrevit_config.ini files on the computer after install:
![image](https://user-images.githubusercontent.com/44774905/148274060-1aebc9df-2a35-4169-a521-47af6d0b89fd.png)
This happens when I try to install the admin version also. A config file will exist in the User folder and in the ProgramData-folder.

The admin version works best, but after I use the workaround by deleting the config-file and copying the text back in, other users on the machine will still get the:
`Exception: Failed seeding config file. | The process cannot access the file 'C:\ProgramData\pyRevit\pyRevit_config.ini' because it is being used by another process.`

Installing with CLI is not working for me either.

Right now, I have no way to reach all users on a machine with pyRevit without bugs :(

**Comment by eirannejad** [comment]
Same as https://github.com/eirannejad/pyRevit/issues/1451
Please follow conversation there
