### ISSUE TITLE
Idea: Add support for C# assemblies

### ISSUE THREAD

**Issue by shtirlitsDva** [eirannejad/pyRevit#143]
Hi

I would like to propose adding support for loading c# assemblies.

**Comment by shtirlitsDva** [comment]
To elaborate:

So instead of loading a python script, a button would execute an IExternalCommand from a c# assembly (a bit like "Add-in Manager" in the SDK).

**Comment by eirannejad** [comment]
@shtirlitsDva @jeremytammik @gtalarico  I'm glad you mentioned this. pyRevit currently supports C# scripts. It compiles them at runtime and creates executable commands for IExternalCommand and also supports IExternalCommandAvailability. Take a look at the button bundle listed below. It only has a `.cpp` file instead of a `.py` file. This is a work-in-progress feature and thus not announced yet, but technically you can create c# bundles now. The unfinished component of this feature is that I need to make the compiler smart about the assemblies it needs to reference for the C# script to work. Currently it references these assemblies by default (Which is plenty for most commands):

- RevitAPI
- RevitAPIUI
- IronPython
- IronPython.Modules
- Microsoft.Dynamic
- Microsoft.Scripting
- Microsoft.CSharp
- System
- System.Core
- System.Drawing
- System.Windows.Forms
- PresentationCore
- PresentationFramework
- WindowsBase

Here is the bundle folder:
`pyRevit\extensions\pyRevitCore.extension\pyRevit.tab\pyRevit.panel\Labs.pulldown\Test C# Script.pushbutton`

**Comment by jeremytammik** [comment]
wow, that is a brilliant suggestion and a brilliant enhancement! cool work! well done! this might make a huge difference for future directions... thank you!

**Comment by eirannejad** [comment]
Yes sir. Also, you can modify the C# code on the fly and reload pyRevit without closing your Revit :+1:

**Comment by jeremytammik** [comment]
that was the very first thought that entered my mind  :-)

**Comment by jeremytammik** [comment]
can i share this on the blog or would you prefer to publish it elsewhere first yourself?

**Comment by eirannejad** [comment]
@jeremytammik Oh no feel free to share as you wish. Just mention that it's work-in-progress and I would appreciate anyone's contribution to make it better. Thanks a bunch

**Comment by gtalarico** [comment]
awesome, as always!

**Comment by andrewberes** [comment]
I would like to follow up about the ability for smart references for assemblies be it custom or otherwise, and if there was any progress on this.

Basically, i would like to load a .cs script in the same way as a .py as you mentioned above, however in my script i reference another .cs file for various classes. The other file is named ClipperLib.cs and i use it to conduct a topological operation on a set of boundary curves to generate filled regions. I have that ClipperLib.cs file located within the same .pushbutton folder currently, but i don't know how to reference it.

I have scanned through the various Revit API forums and currently use pyRevit to deploy my company wide tools. I apologize if this is a naive question, i am only a novice - but any help getting the references to work is greatly appreciated!

See my references below.

using System; 
using Autodesk.Revit.UI;
using Autodesk.Revit.ApplicationServices;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.Architecture;
using Autodesk.Revit.UI.Selection;
using System.Collections.Generic;
using System.Linq;
using System.Diagnostics;
using ClipperLib;
using Polygon = System.Collections.Generic.List<ClipperLib.IntPoint>;
using Polygons = System.Collections.Generic.List<System.Collections.Generic.List<ClipperLib.IntPoint>>;

**Comment by eirannejad** [comment]
Great question. I haven't gotten the time to work on this. Currently pyRevit compiles the .cs files on the fly at load time. What I want to do it to run the .cs files just like a script on every button click. I'll add this to the improvement ideas and will refer to this

**Comment by alitehami** [comment]
@shtirlitsDva @eirannejad 
Although this issue is Closed, thought to share a finding that might answer the initial question:

have a look at the script here, on my github:
https://github.com/alitehami/pyRevitBetaIdeas_Public/blob/master/aliTehami.extension/BetaConcepts.tab/invoking%20Assemblies.panel/invoke.pushbutton/script.cs

[you can test with the TestAssembly.dll (an empty Revit Addin 2017, with a TaskDialog Test Command only )](https://github.com/alitehami/pyRevitBetaIdeas_Public/tree/master/aliTehami.extension/BetaConcepts.tab/invoking%20Assemblies.panel/invoke.pushbutton/)
