### ISSUE TITLE
Incompatibility with other plugin

### ISSUE THREAD

**Issue by felixcharvin** [eirannejad/pyRevit#1484]
Hi,
I'm developing a Revit plugin for a company and I encounter PyRevit error at Revit loading when my plugin is installed. You can check the error in the screenshot below.

I have tested on Revit 2020 and 2021 with PyRevit 4.8.8 on Windows 10.
Do you have any idea of what could cause this issue? I think it's problem of package version but not sure. 

Here is a list of packages i'm using in my plugin:
- MaterialDesign
- Newtonsoft.Json
- PdfSharp
- MahApps.Metro
- FontAwesome
- Flurl
- ControlzEx

How could I solve this problem if we are not using same version of package? (I tried with ILMerge or ILRepack but without success)

Thanks for help!

![Capture d’écran 2022-02-14 112146](https://user-images.githubusercontent.com/19908633/153845946-d59df2a6-51b1-4a80-b4d0-b5ec4db7aa62.png)

**Comment by FredTHT** [comment]
Hi @eirannejad ,

I'm the product manager of the company which is deploying the plugin Felix is speaking of.

Sorry to put pressure on you, but I confirm the criticality of this issue, for both of our plugins. If your plugin is already installed, ours doesn't work, but if our plugin is installed, yours doesn't work...
And at the end of the day, these are our users that are penalized...
We are not competitors, as our plugin are not covering the same functions, so this is important that they can be installed together.

May be you have already encountered this kind of issue, and your help would be precious.. 

Thanks in advance for your attention !
Kind regards,
Frederic

**Comment by eirannejad** [comment]
Does replacing the dlls inside the pyRevit folder, with the ones provided by the conflicting plugin solve the issue? The real problem is the dotnet runtime. I highly advise to compile your plugins against a "specific" version of those dlls so the dotnet runtime does not resolve to any already loaded dll of the same name.

Let me know if replacing the dlls solves the problem. As far as I can remember pyrevit only uses `ControlzEx.dll` in the list above and has custom compiled dlls for `MahAppsMetro.dll` (`pyRevitLabs.MahAppsMetro.dll`)

**Comment by felixcharvin** [comment]
Hi,
we have rebuilt all packages used in our plugin with a different name to be sure there will be no more conflict.
The problem is solved.

**Comment by jmcouffin** [comment]
Same goes for the BIMxr plugin

Jiminy Cricket told me :
> ControlzEx.dll BIMrX is using v5.0.1.15 and pyrevit bin includes 3.0.2.4.

**Comment by jmcouffin** [comment]
Updated the ControlZeX.dll to V6.0 for .NET Framework v4.0 with #2011
