### ISSUE TITLE
Extension Dependency

### ISSUE THREAD

**Issue by gtalarico** [eirannejad/pyRevit#154]
I updated my pyrevitplus scripts to use rpw.
Scripts seem to be working fine, but I am guessing anyone who installs it will run into errors due to the missing rpw.

Since some extensions can be libraries, we might need to think about how we could deal with dependencies:

```
        {
        "builtin": "False",
        "type": "extension",
        "name": "PyRevitPlus",
        "description": "Extensions for PyRevit",
        "author": "Gui Talarico",
        "author-url": "https://github.com/gtalarico",
        "url": "https://github.com/gtalarico/pyrevitplus.git",
        "website": "https://github.com/gtalarico/pyrevitplus",
        "image" : ""
        "dependencies": ["RevitPythonWrapper"]     # <<<<<<<<<<<<<<<<<<<<<<  EXAMPLE
        }.
        {
        "builtin": "False",
        "type": "lib",
        "name": "RevitPythonWrapper",
        "description": "A Python Wrapper For the Revit API",
        "author": "Gui Talarico",
        "author-url": "https://github.com/gtalarico",
        "url": "https://github.com/gtalarico/revitpythonwrapper.git",
        "website": "http://revitpythonwrapper.readthedocs.io/en/latest/",
        "image" : "http://revitpythonwrapper.readthedocs.io/en/latest/_images/logo-tight.png"
        },
```

**Comment by hdm-dt-fb** [comment]
@gtalarico thanks for pointing that out! I was thinking about that question as well. I like that your proposal works a lot like a requirements.txt. But could this maybe even happen on per-script level? So if I PR scripts into pyRevit, I probably should not bundle each of them with an additional copy of revipythonwrapper as a lib.
@eirannejad Maybe by placing an optional requirements.txt in the script.py folder so that a pyRevit mechanism could ckeck if they are met and notify the user could be a way, or is that a bad idea? That could save us a lot of checks or less elegant lines (without wrapper / pyRevit std lib) inside our script.py. 
Just thinking out loud: Maybe that could be even extended into a param exists in project check, too?
Let me know if all that checking sounds too crazy.? Thanks!

**Comment by eirannejad** [comment]
Yes yes all good ideas. I'll start working on this. Before I finish up the extensions system I had two parameters that could be defined inside the scripts but they're not implemented as of now.

I think the scripts should be able to require the min/max host and pyrevit versions:
`__min_compatible_revit_ver__ = '2015'`
`__max_compatible_revit_ver__ = '2017'`

And then their containing extension can define the extension dependencies that are required for its scripts (as proposed by @gtalarico):

`"dependencies": ["RevitPythonWrapper"]` will be added to the extension definition

Let me know of your thoughts.

**Comment by gtalarico** [comment]
Perfect! 
and agree on min/max year. If I am not mistaken, we had discussed this in the past.
Sometimes I sort of do this manually by checking the year and some scripts, and exiting if it does not meet criteria.

**Comment by eirannejad** [comment]
**Update: Implemented script compatibility params**
`__min_revit_ver__` and `__max_revit_ver__` could be used to define the compatible host versions. The script will not load on an incompatible version. Extended tooltip shows the compatibility params

**Comment by eirannejad** [comment]
Implemented
