### ISSUE TITLE
Messy display pushbutton when using Chinese string as a title

### ISSUE THREAD

**Issue by Lemonlee8** [eirannejad/pyRevit#161]
Hi, eirannejad,
The pyRevit help me a lot, thank you very much.
But One imperfect thing  that I came across is : When I use a Chinese string as the "script.py" title, reloaded it, the pushbutton name changed to be messy display. English string works very well. 
The code is like this:
```python
# -*- coding: UTF-8 -*-
__doc__ = u'自动楼梯编号'
__title__ = u'自动楼梯编号' 
__author__ = 'Ben'
```
And the UI button is like this:
![image](https://cloud.githubusercontent.com/assets/7747035/23392317/bcc52b34-fdb5-11e6-816e-6ef35c44c472.png)

Can you make pyRevit support the Chinese, or give me some idea for it? Very thanks...

**Comment by eirannejad** [comment]
@Lemonlee8 Hi! Absolutely, you're most welcome. I hope you enjoy it and add awesome tools to it.
The Chinese button works perfectly on mine. This issue came up before on another language and we fixed it. What version of pyRevit are you using? Are you keeping it updated?

![chinesebutton](https://cloud.githubusercontent.com/assets/8197916/23441260/1edef398-fdd6-11e6-9fad-57f3374f73f0.png)

**Comment by Lemonlee8** [comment]
Good,When I pulled code  from remote, it worked perfectly....Now I can write addins with Chinese pushbuttion:))) Thanks!
![image](https://cloud.githubusercontent.com/assets/7747035/23446285/ee6345be-fe7c-11e6-9fe8-76138c94c366.png)

**Comment by eirannejad** [comment]
Awesome! They look really cool! 👍
