### ISSUE TITLE
Add pySideX/pyQTX to the embeded cpython engine

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#1628]
I would like to have the pySide2 libs added to the cpython engine. 
This would make gui-creation with cpython much easier and would be an alternative to WPF.
Thank You

**Comment by MacNeill1992** [comment]
tkinter / PySimpleGUI would be nice as well..

**Comment by eirannejad** [comment]
@tillbaum 
- Have you tested `pySide2` with Revit? Any examples I could use to get started with?

@MacNeill1992
- Adding `tkinter` is not possible since we don't have any control over the main application (Revit) and `tkinter` requires a set of properties on the main app window class.
- Seems like `PySimpleGUI` is a wapper library that could use QT as backend same as `pySide2` right?
