### ISSUE TITLE
Failing to fully install thru sccm

### ISSUE THREAD

**Issue by moyersdssoe** [eirannejad/pyRevit#1642]
We are trying to mass deploy this application thru SCCM using the admin_signed.exe, and using the /SILENT switch.  Problem is that it does in fact install as can see the C:\Program Files\pyRevit-Master folder and files within it, but it fails to push the .addin file to the C:\ProgramData\Autodesk\Revit\####\Addins location for each version of Revit installed.  Thus when launching Revit it never shows up in the ribbon.  A side note is that if we run the same installer from our ccmcache folder where SCCM pulls the installer locally to each machine, then you go thru the prompts that were silenced by SCCM and it installs the same - takes about 10 seconds longer but it does push the content to the said folders for the .addin file.  I also noticed that when running it manually it creates a pyRevit folder under my user profile as well?  Can you help me out with proper switches that should be used in setting up the deployment correctly?

Thanks,
Dan

**Comment by Mic-94** [comment]
I have same issue, it's installing correctly when I change installation behavior to user but I'm still looking for other workarounds.

![obraz](https://user-images.githubusercontent.com/82094596/198236768-abdc08fc-a2f7-491b-8bc2-3e6f7b5484bc.png)

It's seems like installer have problem with system context, it's strange because when I install it from psexec -s -i cmd it's working fine.

**Comment by moyersdssoe** [comment]
We are running it from a system account.  I will add, that we resolved by writing a bat file to make directories if not existing, and place the .addin files into these locations for each version of Revit that we are running and that allowed it to work, but without using this bat file it never would create these .addin files into the folders as needed to see in the Revit ribbons.
