### ISSUE TITLE
Copy sheet with views between projects

### ISSUE THREAD

**Issue by thibaultmasson01** [eirannejad/pyRevit#1657]
Hi,
I use the button "Sheets - Copy Sheets To Open Document". It works well for sheets/legends/annotations on sheets.
However, for views like floor plans or sections - that do not yet exist in the open Document - , it does not work. Is it normal ? If yes, do you have a workaround to solve this issue?
Ideally, I would like to copy the views with annotations (texts, lines, filled regions, etc), tags, and dimensions.
Thank you in advance.
Sincerely,
Thibault.

**Comment by SNHAjared** [comment]
@thibaultmasson01 what you are asking for can't be done because Plans, Sections, and Elevations are Model Views- they display 3D model geometry. There is no way to locate/align the incoming views to the model they are coming into. This tool only makes sense to use for views that are separate from any 3D geometry, and so only works for Drafting, Legend, and Schedule views.

**Comment by thibaultmasson01** [comment]
Hi, OK thank you for your reply. We decided to attach the link in the project. We lost dimensions, but we kept all sheets with views and annotations at the right place.
