### ISSUE TITLE
pyRevit "Reporting issues" Notion page indexed by Google as the Notion app bug report instruction page in Google

### ISSUE THREAD

**Issue by benediktschroder** [eirannejad/pyRevit#1722]
In Notion, if you want to add a date in the past which is January 31 (for example January 31, 1797), it automatically puts "January 30".

1. Go to a table
2. Add a new property of the type "Date"
3. Add a new date in a row
4. Put January 31, 1797 
5. Now see what gets written in the cell: January 30, 1797

This may seem like an unnecessary date, but in our database we need anniversaries, also from composers from the classical/baroque time. It also produces errors with additions/substractions of dates in the formulas.

My Notion:
Notion 2.19.23.11.0.34
Desktop 2.0.34
Updated 3 days ago

Thanks for fixing!

**Comment by jmcouffin** [comment]
Wrong repo @benediktschroder

**Comment by benediktschroder** [comment]
> Wrong repo @benediktschroder

Google: "Notion bug report" ->
https://www.notion.so/Reporting-New-Issues-f1fdd62cf6074b318bfe8ddfbc2d8d98

WTF is this website?!

**Comment by jmcouffin** [comment]
@benediktschroder you are right, google return pyRevit repo documentation in Notion as a first result!
Kind of funny.
@eirannejad you need to change the title of this page https://www.notion.so/Reporting-New-Issues-f1fdd62cf6074b318bfe8ddfbc2d8d98 so that it does not get indexed as a Notion app page and mention pyRevit in its title more evidently.

**Comment by jmcouffin** [comment]
Same goes for #1723
