### ISSUE TITLE
Linkify Buttons & other clickable items not working in console window

### ISSUE THREAD

**Issue by datcomputerguy** [eirannejad/pyRevit#1726]
**Describe the bug**
Just got a new computer. Windows 11. Installed Revit, latest pyRevit, and added my custom extension folder. It appears that my scripts are running just fine. But when I try to use a button or clickable element in an output console window for instance a button generated by linkify it does nothing. Can’t seem to find an error, warning, or anything. Just does nothing. 
Tried this on 3 other new computers and the same problem exists.
I thought maybe there was an Intune or Defender policy blocking something?  But I have looked at their logs and don't see anything.

Additionally I just noticed when I run some of the official pyrevit tools that have a hyperlink to the author in the output, clicking the link does nothing as well.

**To Reproduce**
1. Run any script that outputs a Linkify button.  (screenshots I ran the built in "Find All Revised Sheets" script)
2. Click the button in the Console Window.
3. Nothing happens.

**Expected behavior**
Clickable buttons to function in console window as expected.

**Screenshots**
<img width="734" alt="image" src="https://user-images.githubusercontent.com/3844234/217061670-36ec97f2-4d48-4a98-9a6d-2b3810a17ffc.png">
If you click the elementid button or the search button, nothing happens.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/3844234/217061819-b068443d-87a1-461b-8531-e8a3081d3d7c.png">
If you click this hyperlink that should take you to the author, nothing happens.

**Desktop (please complete the following information):**
 - OS: Windows 11 pro
 - pyRevit Version: 4.8.12.22247+0031
 - pyRevit Environment: 
```C:\Users\patrickm>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2021" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "Autodesk Revit 2020" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
PatricksExtension | Type: Unknown | Repo: "" | Installed: "C:\Users\patrickm\OneDrive - R&N Systems Design\pyRevit\PatricksExtension.extension"
==> Default Extension Search Path
C:\Users\patrickm\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\patrickm\OneDrive - R&N Systems Design\pyRevit
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
Autodesk Revit 2021 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
Autodesk Revit 2020 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Additional context**
We do have Windows Defender/Intune installed on these machines that was causing some issues with other software, but it appears that the scripts, Python, etc are all functioning fine.  Its just the clickable buttons don't do anything.

**Comment by crumpGavin** [comment]
+1 Has begun affecting us since we switched to Windows 11 organization wide.

No bugs/issues aside from the buttons not responding to the clicks.

Curious to find out if there are known causes of the issue as have seen a few people come across this. Likewise we use Intune so wondering if that may be a cause for myself or other users.

**Comment by jmcouffin** [comment]
I will close it as it is solved by original poster.

**Comment by Texmati** [comment]
What was the solution to getting the links to work on Windows 11, exactly?

**Comment by jmcouffin** [comment]
> What was the solution to getting the links to work on Windows 11, exactly?

Really?
Two comments up: https://github.com/pyrevitlabs/pyRevit/issues/1726#issuecomment-1828388977

**Comment by Texmati** [comment]
"I basically did a process of elimination for all of the settings and **gave up** once I reached this set."    

Sorry if I'm missing something, but the 'giving up' part, didn't make that sound like a solution that necessarily worked . . . but I guess  you're saying that the linkify links should work again in Windows 11 after adjusting security settings per what's shown in that PDF?  Was the offender never narrowed down to specific settings?

**Comment by datcomputerguy** [comment]
This is still what I'm using at my company and it's still working!
I gave up figuring out exactly which of those settings was the problem.
But it's definitely a couple of those in the pdf lol.

**Comment by Texmati** [comment]
@datcomputerguy    Thanks for the clarification!

**Comment by Texmati** [comment]
<html>
<body>
<hr>
<h2>pyRevit Linkify — Security Investigation Summary</h2>
<h3>Claude's Analysis: Most Likely Culprit Settings</h3>
<p>Given that linkify uses an embedded browser control firing a <code>revit://</code> custom protocol handler, the following IE security zone settings are the most relevant — and most likely misconfigured:</p>

Setting | PDF Baseline | Risk if Different
-- | -- | --
IE Internet Zone — Launch apps/files in an iFrame | Disable | A hard block could prevent protocol handling entirely; "not configured" may inherit a more restrictive GPO
IE Internet Zone — Logon options | Prompt | More restrictive values can interfere with the browser control handing off to the custom protocol handler
IE Internet Zone — Security warning for potentially unsafe files | Prompt | A more restrictive setting (e.g., Disable) could silently block the launch
IE Internet Zone — Protected Mode | Disabled | Strong candidate — if Enabled in your org, sandboxing silently blocks inter-process communication with the Revit process


<blockquote>
<p><strong>Most likely culprit:</strong> Protected Mode enabled vs. disabled is a significant behavioral difference that would produce exactly the <em>"click the link, nothing happens"</em> symptom, because the <code>revit://</code> handler needs to communicate back to the Revit process, and Protected Mode sandboxing can silently block that inter-process handoff.</p>
</blockquote>
<hr>
<h3>IT's Response: Why These Can't Be Changed</h3>
<p>All four settings belong to the <strong>legacy Internet Explorer security zone model</strong>, which has been effectively deprecated since 2022. The org's baseline intentionally moves away from these settings per industry-standard cybersecurity practices. Relaxing them to support a custom protocol handler would mean accepting documented enterprise risks:</p>
<ul>
<li>Credential exposure</li>
<li>Sandbox escape vectors</li>
<li>Drive-by execution vectors</li>
</ul>
<p>...in exchange for a workflow convenience — which IT considers an unacceptable trade-off at this time.</p>
<hr>
<h3>IT's Recommendation for pyRevit</h3>
<p>Migrate the linkify feature away from the legacy IE control to a currently approved technology:</p>
<ul>
<li><strong>WebView2</strong> — Microsoft's modern embedded browser component</li>
<li><strong>Local loopback endpoint</strong> — serve the protocol action via <code>localhost</code></li>
</ul>
<p>Either approach could likely function within the org's existing security posture <strong>without requiring policy exceptions</strong>.</p></body></html>
</body>
</html>

**Comment by jmcouffin** [comment]
> Migrate the linkify feature away from the legacy IE control to a currently approved technology:
> 
> * **WebView2** — Microsoft's modern embedded browser component
> * **Local loopback endpoint** — serve the protocol action via `localhost`

Yep yep. 
Something we know about. The output window relies on the webbrowser .net object.
If you are willing to go down this rabbit hole, while maintaining features parity, go ahead
