### ISSUE TITLE
Include View References in Open Referring Views and/or Query View Referencing 

### ISSUE THREAD

**Issue by RevitIRL** [eirannejad/pyRevit#1740]
**Is your feature request related to a problem? Please describe.**
I had a live detail that had to move. Because it was also rotating, I found it easier to just cut a new section and copy the annotation over. However, then I realized that it was a "master detail" after I removed it from the sheet (and a bunch of View References on the sheet went blank). I want to double-check that it's not also referred to on any other sheets, but the only "reference" given by pyRevit is the plan sheet that it's cut on.

**Describe the solution you'd like**
Include View References (just like plans, etc.) in pyRevit > [Drawing Set] > Views > Open Referring Views & Query View Referencing 

**Describe alternatives you've considered**
I guess I could search the PDF...

**Additional context**
current project's in Revit 2020.2.7

**Comment by thumDer** [comment]
Can you please provide more details to replicate your issue? What is the master detail, how the other view references are created (callouts?) what was on sheet, what wasn't. If you could provide a simple example model for testing that would be great!
I have to tell you that the way Revit handles these _Referenced_ relations is quite sketchy, and however I only had a quick peek at the code, my initial feeling is it would quite difficult to solve in pyRevit, because of Revit.
