### ISSUE TITLE
Request: Ability to split walls vertically.

### ISSUE THREAD

**Issue by JMarshQPK** [eirannejad/pyRevit#1741]
Revit allows splitting of walls horizontally (like in plan), but there is not a good way to split walls vertically (like in elevation).
The current workflow is duplicate wall in place and stretch one up and the other down to the correct location. The stretching causes havoc with hosted elements like windows and the process duplicates all wall hosted elements. 

An ideal workflow would be:
1. Select custom splitting tool from toolbar
2. Select wall to be split vertically in Revit viewport
3. Provide absolute elevation for the split to occur (or click to split like the current tool acts in plan)
4. Walls stack at the given split elevation while maintaining the hosted elements/annotations/tags/dimensions

**Comment by dvdgnz** [comment]
FYI I know it's not as flexible as what you have described, but you can split walls in elevation and sections using the split tool if they are cut in the view

**Comment by karthi1015** [comment]
It would be great if this is added to pyrevit. Its easy to select levels/reference planes to split walls at intersections this would speed up the process of splitting multiple levels at once. It's a tedious process to do this manually Revit selection in elevations/section since split command is not perfect at splitting at the right location it grabs some weird references when this is done manually like a few inches off of the level line and requires manual cleanup.
