### ISSUE TITLE
Sentinel One Closes Revit when pyRevit is installed

### ISSUE THREAD

**Issue by sjdejesus** [eirannejad/pyRevit#1751]
I am using a PC.

Downloaded and installed Pyrevit,

Launched Revit, it opens and closes. It won't completely launch. No error message.

Uninstalled Pyrevit, and Revit launches with no problem.

Something wrong , Please help.

**Comment by sjdejesus** [comment]
Our company uses SentinelOne Guard.

**Comment by carlom27** [comment]
Same issue is happening on our end all of a sudden. Installed Pyrevit a couple weeks ago on a new laptop which was working fine with no errors or crashes until this morning. My company is using SentinelOne as well however I do not see how that would be cause for issue as, like previously mentioned, Pyrevit and Revit was working together normally without issue prior to today. 

Would be good to get a fix or some answers on this as Pyrevit is essential to some of the workflows we use in office.

**Comment by Davelv426** [comment]
I have the same issue. I am using windows 10, Revit 2021, 2022 & 2023. When I install Pyrevit, I can't launch any Revit versions. When I uninstall Pyrevit I'm fine. Pyrevit was working fine for a couple of years, then recently not.

**Comment by jmcouffin** [comment]
> morning. My company is using SentinelOne as well however I do not see how that would be cause for issue as, like previously mentioned, Pyrevit and Revit was working together normally without issue prior to today.
> 
> Would be good to get a fix or some answers on this as Pyrevit is essential to some of the workflows we use in office.

@sjdejesus @mc93-archi 
Sentinel one has been know to block pyRevit and therefore crash Revit at launch.
most of the people using sentinel one have been whitelisting pyRevit and then everything came back to normal

**Comment by jmcouffin** [comment]
see https://github.com/eirannejad/pyRevit/issues/1724

**Comment by jmcouffin** [comment]
I sent a request for support to get pyRevit whitelist by default to Sentinel... Weeks later, no reply.

**Comment by Paddy32** [comment]
Has this been solved ? We can't install pyrevit on any of our machines because either Revit closes or we get the Python error message. We're spending so much time and energy to make Pyrevit work, we need it simply to add colours to tabs.

Do you know a simpler solution or other plugin (Pyrevit Light?) that can simply put colours on tab in Revit ?

**Comment by jmcouffin** [comment]
> Has this been solved ? We can't install pyrevit on any of our machines because either Revit closes or we get the Python error message. We're spending so much time and energy to make Pyrevit work, we need it simply to add colours to tabs.
> 
> Do you know a simpler solution or other plugin (Pyrevit Light?) that can simply put colours on tab in Revit ?
@Paddy32 
Same answer as in the other closed issue/
There is no pyrevit light.

**Comment by Davelv426** [comment]
It has for me, since pyRevit can’t get past SentinalOne security I can’t use pyRevit anymore.

David Meza

Bay Area Builders, Inc.
3360 De La Cruz Blvd
Santa Clara, CA 95054
669-342-9200 cell
www.ba-builders.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__urldefense.com_v3_-5F-5Fhttp-3A_www.ba-2Dbuilders.com_-5F-5F-3B-21-21P4LiPV1inDXhLQ-210bbSbI6MkJtadzmifRupsL86EwqbktJkhw5N7IVT5EHXflwekjAwjFs9ADxz7ySU5AIzcysi8Uw18ShZ1z41rZlI6DYbjts-24&d=DwMGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=PjEQ8m40O4STUa5EIpwO4ACJZO0R6rf7R1NKPKM6suo&m=yXWSsRU-QxdbjAZotLC45gGPicBzkOj1GwgMAxq2l3CwP0EXVYOsE_FdfQyM6D5r&s=AsCeQVMqWWORGEIrLJZFvU3PneafYRHqanEogp-gWec&e=>
