### ISSUE TITLE
pyRevit script hook for open model event possible?

### ISSUE THREAD

**Issue by hdm-dt-fb** [eirannejad/pyRevit#201]
Hi @eirannejad ,

I was wondering if it would be possible to have a pyRevit script trigger, when certain events happen like model open? Is there already some kind of event loop?

The background is: 
With [rvt_model_service](https://github.com/hdm-dt-fb/rvt_model_services) I introduced an audit open ( in our office @lunch break), which tells people (when they are back from lunch), whether their project central file is fine or corrupted. (should reduce worst case roll-back duration to half a day)
Additionally to that I would love to find a way to notify people when they open a/that file, that it might be "hidden corrupt" (opens fine regularly, but tells about it's corruption if opened with audit)

Best, F

**Comment by eirannejad** [comment]
Handling events in Revit API works like this:

``` python
from System import EventHandler, Uri
from Autodesk.Revit.UI.Events import ViewActivatedEventArgs, ViewActivatingEventArgs

def event_handler_function(sender, args):
   # do the even stuff here

# I'm using ViewActivating event here as example.
# The handler function will be executed every time a Revit view is activated:
__revit__.ViewActivating += EventHandler[ViewActivatingEventArgs](event_handler_function)

```

See the Events section on these classes for the events that could be handled as shown above.
UIApplication: http://www.revitapidocs.com/2017.1/fb46d2bd-92bf-1cc5-79ad-f253f3e875d8.htm
ControlledApplication: http://www.revitapidocs.com/2017.1/b69e9d33-3c49-e895-3267-7daabab85fdf.htm

**Comment by hdm-dt-fb** [comment]
ahh nice!! 
thank you so much for snippet and links!!

**Comment by gtalarico** [comment]
This great. Does the event stays registered after the externalcmd is done executing???

Also, ehsan, would you mind if I add the snipped to revitapidocs.code?

**Comment by eirannejad** [comment]
Yes once the event handler is added to the handler list, it will be called on any occurrence of that event.
See the `Sync Views` tool as example.

Of course it is! :D you have full admin rights to anything on pyRevit.

**Comment by gtalarico** [comment]
😀

**Comment by Matt-Olsen** [comment]
This is super helpful thanks Gui and Ehsan. I'm wondering whether it would be possible to have an event handler that is triggered when a view is activated, but for this to be added to the handler list at the point of the Revit application opening, rather than the user having to click a button? (ie, so it is always functioning?)

**Comment by hdm-dt-fb** [comment]
hi @Matt-Olsen,
yes, it is. you can build on the pyRevit startup.py example.
it will start with your Revit instance. from there you can register to events.
as an example you could hook up a python function on_opened 
in startup.py with the model opening:

```python
def on_opened(sender, args):
    if doc.IsWorkshared:
        pass

uiapp.Application.DocumentOpened += EventHandler[Events.DocumentOpenedEventArgs](on_opened)
```

**Comment by Matt-Olsen** [comment]
That makes sense - thanks so much! I'll have a play around with this.

**Comment by hdm-dt-fb** [comment]
you are welcome, 
it is quite the powerful tool, with many useful use-cases (imho), 
so thanks to Ehsan for implementing it! 🙂 
@Matt-Olsen the only "catch" is, that you do not have a window by default, 
where print statements and error messages would go, so I recommend logging to a file.

**Comment by htlcnn** [comment]
pyRevit has hook system that help you add hooks automatically:
https://www.notion.so/Extension-Hooks-b771ecf65f6a45fe87ae12beab2a73a6?p=24f42c8fb39c4fa3981296a40cb6dd64

**Comment by Matt-Olsen** [comment]
Thank you both. I've been reading through the PyRevit documentation on hooks and telemetry - there seem to be some powerful possibilities and I just need to wrap my head around how it will be implemented in our practice. 

One tool I would like to develop would override the 'Comments' field when users sync with a particular code, related to what they were working on (eg different drawing sets or building packages), so that we could quantify time spent in different areas.

I noticed the comment string exists in the arguments for the sync event. Would PyRevit allow me to override this comments field, or does it only 'listen' to whatever comment the user inputs? (it's very difficult to get people to fill this in, reliably..)

**Comment by tillbaum** [comment]
Hello, I cannot unsubscribe from any event regularly. I haven't figured this out why it sometimes seems to work and sometimes doesn't at all. There are some links covering this problem, if you use Google.

**Comment by eirannejad** [comment]
@Matt-Olsen No the event args are readonly properties

@tillbaum Would you mind elaborating on how you want to "regularly" unsubscribe from an event? Code examples? are you using hooks?

**Comment by tillbaum** [comment]
Sometimes you could let the user deside if he/she wan'ts a certain function to be automated (i.e.: hooking up to an event)
--> checkbox checked on a WPF Form.
