### ISSUE TITLE
PyRevitLoader error loading pyRevit

### ISSUE THREAD

**Issue by CharzAznabel** [eirannejad/pyRevit#2070]
Hello PyRevit Community,

I've looked into this issue in the forum, The solution was uninstall and reinstall, I've done that and it didn't work in my case.

Could you assist in this when time allows? the installer version I used **pyRevit_4.8.14.24016_signed**

![image](https://github.com/eirannejad/pyRevit/assets/25690184/68a1abbb-f2c0-49a2-83ca-1c6fc9fe403d)

**Comment by jmcouffin** [comment]
Please have a look at https://github.com/eirannejad/pyRevit/issues/2035 and https://www.notion.so/pyrevitlabs/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7#ee9590e3dd8d4920b8b09ecb3c42d993
if followed thoroughly, these steps solve the issue 99% of the time.

Please, when you submit the issue, follow and fill in the template so that it gives a bit of context.

**Comment by jmcouffin** [comment]
a good recap here https://discourse.pyrevitlabs.io/t/new-release-error-dynamically-compiling-pyrevit-runtime/2621
try to follow these
and wave  👋 if you did not manage in the end
