### ISSUE TITLE
Add intermediate folders (e.g. folder.folder)

### ISSUE THREAD

**Issue by pjhfggij** [eirannejad/pyRevit#2114]
## Is your feature request related to a problem? Please describe

Accessing scripts inside nested bundles/folders is too easy right now - scripts inside buttons inside panels inside tabs inside extensions take only one eternity to open. 

## Describe the solution you'd like

It could be significantly slowed down by addition of new .folder bundle type. For example this:

```
extension
  tab
    panel
      pushbutton
        script.py
```

could become

```
extension
  folder
    tab
      folder
        panel
          folder
            pushbutton
              folder
                script.py
```

This obviously only scratches the surface. [Windows allows for many more nested folders](https://superuser.com/questions/1624192/how-many-folders-can-i-put-in-one-windows-folder). Sky is the limit!

## Describe alternatives you've considered

Jumping off a bridge

## Additional context

In Rhino it takes no effort to run a python script (custom command invoked from a command line). I'm seriously upset how complicated pyRevit makes it.

**Comment by sanzoghenzo** [comment]
@pjhfggij , seriously???

If you don't like the tool, either help make it better and ask for features constructively, or just don't use it. Opening this issue was the worst thing you could have done. I was willing to fix things to accommodate your previous request, but now I'm evaluating to ignore all of your posts.

This project is not backed by a big corporation and the quality of the product relies on a few volunteers. 

That being said, if you only need to run script without having to build a ribbon for your scripts, just use RevitPythonShell, and redirect your anger towards that project.
