### ISSUE TITLE
Newbie needs a little help.

### ISSUE THREAD

**Issue by LP31** [eirannejad/pyRevit#217]
Thank you offering such a great tool for us!

I'm a mechanical engineer, so most of built-in tools in pyRevit doesn't help me very well. As a result, I start to learn python and RevitAPI and try to write my own scripts.

I opened a built-in script 'Pick.pushbutton' and use it as an example to learn. The main part of the codes is not very difficult but I'm struggling to understand 5x 'from ... import ...' at the beginning of the codes. (see below)

`from scriptutils.userinput import CommandSwitchWindow`
`from revitutils import doc, uidoc`
`from Autodesk.Revit.DB import ElementId`
`from Autodesk.Revit.UI.Selection import ISelectionFilter`
`from System.Collections.Generic import List`

I could understand the 3rd and 4th 'from...import...' that mean import classes from namespaces. And I could find a full list of namespaces and their classes from RevitAPI doc.

**My question is: where I can find a 'dictionary' where I can search 'scriptutils.userinput', 'revitutils', and 'System.Collections.Generic'? For example, how do i know where to import 'doc' and 'uidoc'?**

I know this might be a very simple and stupid question, but I search the web  and got nothing. Please give me a clue, so I know where I can dig.

By the way, sorry for using such many non-technical words to describe the question.

**Comment by eirannejad** [comment]
@LP31 There are no stupid questions.  We're working on the documentation for the `scriptutils` and `revitutils` modules for now you can learn by looking at the scripts. I would highly suggest getting started with the revitpythonwrapper (`rpw`) module instead. I'm also slowly updating the original scripts to use `rpw` module instead of `scriptutils` and `revitutils`

RPW documentation is here:
http://revitpythonwrapper.readthedocs.io/en/latest/

As for the standard dotnet modules e.g. `System.Collections.Generic` that are not part of the Revit API, please use the Microsoft Developers Network website for the documentation:
https://msdn.microsoft.com/en-us/library/system.collections.generic(v=vs.110).aspx
