### ISSUE TITLE
User Settings

### ISSUE THREAD

**Issue by ilatimerP** [eirannejad/pyRevit#220]
Hi All,
Thanks Eirannejad for the reply.

This has worked great but we are facing an issue when they want to change some settings we get an error. The Setting do work great if in the config file if it is pointing to the UNC path (\\domain.local\Share\Users\username\Appdata\Roaming\pyRevit\prRevit_config.ini) but if it points to the drive letter of the share (t:\Users\username\Appdata\Roaming\pyRevit\prRevit_config.ini) or c drive (c:\Users\username\Appdata\Roaming\pyRevit\prRevit_config.ini) we get an error.

Is there any way that we can get it to load the user configs only from the UNC path?
Cheers
![pyrevit_userconfig](https://user-images.githubusercontent.com/30032694/28557987-19d21556-7153-11e7-9710-56be68b3e1ee.JPG)
![pyrevit_settings_error](https://user-images.githubusercontent.com/30032694/28557988-19d27d48-7153-11e7-842d-04f34b28562d.JPG)

**Comment by eirannejad** [comment]
@ilatimerP I'm not exactly understanding the problem here. pyRevit figures out the config file location by itself and it's always under `%appdata%/pyRevit/pyRevit_config.ini`. You can't change the location of the config file.

The error screenshot is telling me that there is a problem with pyRevit resolving the Revit addin folder (`%appdata%/Autodesk/Revit/Addins`. Please make sure this folder exists

**Comment by eirannejad** [comment]
Made some adjustments that might solve this:
https://github.com/eirannejad/pyRevit/commit/a3a6e77f5935d5801935c5e1c429a9fc0042bb0b

update and let me know please

**Comment by ilatimerP** [comment]
@eirannejad, I have tested it out on a test users and a live one and it is working well now.  I have asked them to do some testing and keep me up to date but it all looks good now.

Thank you for your help.
Cheers

**Comment by eirannejad** [comment]
Super! Thanks. I'll close this for now but feel free to re-open if the issue comes back
