### ISSUE TITLE
PyRevit Implementation Question

### ISSUE THREAD

**Issue by thazell** [eirannejad/pyRevit#233]
Ehsan, 

Have you tried doing an implementation of opening multiple models sequentially and suppressing the warnings?  I've got this to work, but the dialog boxes that pop up during a model open still have to be manually suppressed.  Thoughts?
http://adndevblog.typepad.com/aec/2013/06/dismiss-the-dialog-when-opening-a-copied-central-model-file.html

[Open Files and Execute Command.pushbutton.zip](https://github.com/eirannejad/pyRevit/files/1315492/Open.Files.and.Execute.Command.pushbutton.zip)

**Comment by eirannejad** [comment]
- For batch processing Revit models take a look at:
https://github.com/hdm-dt-fb/rvt_model_services
Runs on python and automatically creates journal files to batch process Revit models. It basically runs a python command on each model and the command can do whatever is wanted.
- Take a look at the `Sync Views` script in pyRevit tools. You can define functions and add them to the `DialogBoxShowing` message handler as described by the article.

I'm closing this since this is not a pyRevit issue but we can continue the discussion.
