### ISSUE TITLE
[Bug]: CPY engine Version in pyRevit About window

### ISSUE THREAD

**Issue by jmcouffin** [eirannejad/pyRevit#2332]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

https://github.com/pyrevitlabs/pyRevit/blob/fde45aa626b1540642d02467222e7e2cc0df1b9c/extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/About.pushbutton/aboutscript.py#L55C1-L60C65 
reports cpy engine version 3.1.2.3 instead of 3.12.3

### ⌨ Error/Debug Message

```shell
-
```

### ♻️ To Reproduce

install pyrevit 5 in 2025

### ⏲️ Expected behavior

reporting 3.12.3
when inquiring the cpyver.Version.ToString() or cpyver.Version.Version, it returns '3123'
- Either we manually split properly 🤮 
- Find the proper version formating

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
-
```

### Additional context

@dosymep @sanzoghenzo

**Comment by sanzoghenzo** [comment]
The problem here is the `".".join(list(str(cpyver.Version)))`.

Unnecessary casting aside (a str is already a list of chars), this expression just adds dots between each number.

There's no way to tell where to put dots automatically, unfortuntately.

The whole thing of using  integers to store the versions is very wrong, if you ask me 😅 it seems to me that it was done to easily compare the versions instead of using a semantic version comparison, but it breaks as soon as you get double digit in one of the parts (major, minor, patch).

For the time being, I would just use `cpyver.Version` as the last agument to `format`, so that we output the version in the same format as everywhere else. (and it would be ready if/when we switch to a proper semantic versioning)

**Comment by jmcouffin** [comment]
> The whole thing of using integers to store the versions is very wrong, if you ask me 😅 it seems to me that it was done to easily compare the versions instead of using a semantic version comparison, but it breaks as soon as you get double digit in one of the parts (major, minor, patch).

Agree

> For the time being, I would just use `cpyver.Version` as the last agument to `format`, so that we output the version in the same format as everywhere else. (and it would be ready if/when we switch to a proper semantic versioning)

I did that locally.
If you are fine with that. I will just do that.
