### ISSUE TITLE
Icon Rules

### ISSUE THREAD

**Issue by andrewberes** [eirannejad/pyRevit#252]
I am having an issue with icons showing up off center and fuzzy even when following the video posted on youTube for downloading them from icons8.

I have the size set to 32px by 32px with a resolution of 72DPI - are there any additional rules for making them appear as they should?

![capture](https://user-images.githubusercontent.com/33666493/32855376-779c50ec-ca0f-11e7-9e11-faceec64ff3f.JPG)

They should appear like this:
![icon](https://user-images.githubusercontent.com/33666493/32855442-a2267432-ca0f-11e7-94d5-c692e4e8c98e.png)
![icon](https://user-images.githubusercontent.com/33666493/32855467-b6977b14-ca0f-11e7-816c-70e61d834e4e.png)

Thanks!

**Comment by eirannejad** [comment]
@andrewberes This issue is general with Revit. The icon DPI needs to be 96 for the icons to show up correctly. Previously `icons8` didn't include DPI in their PNG files but recently they PNG generate system has changed and it adds odd DPIs to the PNGs.

I fixed this issue under the develop branch and I just pushed that as a hotfix to the master. Update your pyRevit and the icons should load correctly. **pyRevit now scales the icons based on the required size for the button and the image DPI**

This change has two benefits:
- You can download icons from any source and use them with pyRevit with no DPI change.
- Icons larger than 32x32 can be used for better icon sharpness on hi-res displays. I'm using 128x128 icons on some of the custom company tools and they look much sharper on my hi-res screen

**Comment by eirannejad** [comment]
@gtalarico

**Comment by andrewberes** [comment]
Awesome! Thanks for the quick response - pyRevit has become by far my most useful add-in. It makes it easy for a beginner to quickly develop custom tools with basic python knowledge! Thanks for all your work!

**Comment by eirannejad** [comment]
Exactly. That was my main motive behind it. All the pyRevit tools are basically a showcase of the python programming for Revit. pyRevit to me is really a rapid-prototyping and development environment.

Thanks for your support.

**Comment by Antonj123** [comment]
Hi Guys,
Sorry to as this question,,, yes i know its a silly one.
I love the coloured icons but i dnt know how i can change them.
Any chance you can explain this to a newbe like me?
Thanks you.

**Comment by baldeModeler** [comment]
Hi,
I am on Revit 2024 but there the icon pyRevit doesn't display. I have changed 32x32 pixel and 96x96 pixel also? thanks.
