### ISSUE TITLE
Icons Being Clipped

### ISSUE THREAD

**Issue by tymokvo** [eirannejad/pyRevit#253]
Some icons are being clipped once loaded into the ribbon. Not sure what layout conditions are causing it, but it happens no matter the icon size or padding.

![pyrevit_issue_icon](https://user-images.githubusercontent.com/12144028/33042710-a73c91c2-cdf7-11e7-9172-0b00d0a858c1.PNG)

**Comment by eirannejad** [comment]
@tymokvo Do you have the most recent pyRevit? Was this working correctly before and it broke after an update?

**Comment by tymokvo** [comment]
commit is # [d4f22600e31c36646372b322141e81867c1f849b](https://github.com/eirannejad/pyRevit/commit/d4f22600e31c36646372b322141e81867c1f849b)
It seems to happen inconsistently across both Revit 2017/2018. i.e. my icons are broken, on a colleagues machine, they are fine. My copies of Revit are the newest service releases (2017.2.3)

![icon](https://user-images.githubusercontent.com/12144028/33089938-13aee9cc-cea7-11e7-9c21-79cebbc1decb.png)

**Comment by tymokvo** [comment]
Ok nvm, updating to the latest commit seems to have solved it

**Comment by eirannejad** [comment]
@tymokvo This hasn’t been a pyRevit issue. The underlying problem is the png DPI that is set inside the png file and is larger or smaller than the default 96 pixel per inch. The png size might be correct but the DPI would cause it to render at a different size. 

The larest pyRevit commit resolves this issue partially but the issue has been completely resolved for pyRevit v4.5 coming soon with high-res icon and screen scaling support.

**Comment by eirannejad** [comment]
yes but if you're downloading icons from the web (especially icons8.com) then the DPI is not guaranteed and you have to edit the icons always. I'd suggest not making any changes to your icons as I have resolved this issue in v4.5. Then you'll be able to use larger icons (I'm using 96x96) for sharper icons especially on hi-res screens. I'll do a video on this soon.
