### ISSUE TITLE
Array of __context__

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#264]
Hello, Ehsan

I think it would be great if developer was able to set not only one \_\_context\_\_ but an array of contexts.

Let me describe my case. Now I'm setting up a button which opens multiple selected views using `uidoc.ActiveView`. But it's also possible to activate a Sheet the same way as View. 

Now I can set `__context__ = "Selection"` but I wouldn't like users to use this button with doors. 

I would like it to look like `__context__ = ["Views","Sheets"]`

I can also imagine some cases when it could be possible to select only specific type of tags, or specific structural element.

Thank you!

**Comment by eirannejad** [comment]
Very good idea. I'm actually working on reworking the availability system to make it faster. I'll add this in for the next update. Thanks for the awesome feedback.

**Comment by eirannejad** [comment]
Resolved. Coming up in v4.5

**Comment by DL-1975** [comment]
First, let me thank you and your team for the great work you are doing.  

I have a script that is modifying only TextNotes elements. 
I thought that using
__context__ = 'Text Notes' 
would make the tool active when only TextNotes are selected.  Currently, the tool is activating if at least one of the selected elements is of 'Text Notes' category.

Thanks

**Comment by sanzoghenzo** [comment]
Hi, FYI that documentation site is deprecated, the official one is [here](https://pyrevitlabs.notion.site/Bundle-Context-630fa1f3611f4ee0aa15d290275e7ef3)

It is better to use bundle.yaml file to have better control on the behavior

The documentation says that it should activate if all the elements selected are of that category; if it doesn't, it may be a bug, or a documentation error (I can't test it right now); try to use the advanced context with the `exact` keyword)

**Comment by DL-1975** [comment]
Thank you very much for your prompt reply.

Your suggestions solved the problem, but new one appeared.

I have a script that adjusts Spot Elevations. The tool needs to be active only when the Spot Elevations are selected. I created bundle.yaml file, and used: 

context: Spot Elevations

but tool becomes active when one of the elements is of Category: Spot Elevations
 I tried with: exact 

context: 
  - exact:
    - Spot Elevations

but this one did not work either. 

The problem is only visual (the tool becomes active when not only Spot Elevations are selected), because the script runs correctly ignoring the elements that are not Spot Elevations.

Any ideas? 
Thank you in advance

Thank you.
