### ISSUE TITLE
 problem when opening Revit

### ISSUE THREAD

**Issue by emetsyuriy** [eirannejad/pyRevit#286]
After installing pyRevit, when you open Revit, this window appears. There is no plug-in in the panel.

![pyrevit](https://user-images.githubusercontent.com/35891276/35481727-fdc44da6-045b-11e8-8035-44143e8b05c1.JPG)

**Comment by eirannejad** [comment]
@emetsyuriy This is a unicode error. It's because you have unicode characters in your system username. pyRevit is trying to get the path to the user temp directory (similar to: `C:\Users\<username>\AppData\Local\Temp`) and is failing in the encodings module. May I ask what's the user name so I can run some tests here and see if I can fix this issue?

**Comment by emetsyuriy** [comment]
username: Tandemdesign. Windows 8.1

**Comment by eirannejad** [comment]
Hmmm. So just to confirm, would you confirm that this directory exists on your machine:
`C:\Users\Tandemdesign\AppData\Local\Temp`

**Comment by emetsyuriy** [comment]
The user name and the user's folder name were different for me. The name of the folder was written by the Cyrillic. I solved the problem by creating a new user.

**Comment by eirannejad** [comment]
So this issue is resolved now with the new username?

**Comment by emetsyuriy** [comment]
Yes.
