### ISSUE TITLE
localisation

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#328]
as some of us are working in a non english environment are there plans to separate messages from code in order to allow localisation in a production environment?

**Comment by eirannejad** [comment]
Uhm honestly I don't have any plans at the moment but I'm open to this and agree it would be super helpful. I need to spend quite a considerable time to go through all the code base for messages and prepare for localization. This is a major problem for me to find that chunk of time.

**Comment by epeter-** [comment]
maybe it were enough if you allow the structure and one (i.e. me) will contribute the dictionary - i would contribute german
peter

**Comment by eirannejad** [comment]
Okay started work on this.

**Method 1: Using `gettext`:**
Initial tests using python native 'gettext' module are promising.

**Required Work/Pros vs Cons:**
- [ ] In all scripts containing user-facing strings,  `from pyrevit.locales import _` needs to be added 
- [ ] All user facing strings in existing code need to be wrapped in `_()`
- [ ] Template `.pot` file needs to be generated from `cpython`; need to write scripts to automate this
- [ ] Translated `.po` files need to be created by translators, then a binary `.mo` to be generated from them
- [ ] Need to figure out a tool chain for keeping the translated `.po` and `.mo` files always updated per new strings added to the code and new `.pot` file.
- [ ] Editing the `.po` files is a bit more cumbersome.

**Method 2: Using a string library module:**
Another method would be to add an internal pyRevit module with standard string values similar to below that could be imported from the desired locale string lilbrary (Similar to using string libraries in cpp and c#).

``` python
# English locale module
# locales/en/messages.py
ABOUT_IRONPYTHON_VER = 'Running on IronPython {}.{}.{}'
```

``` python
# Persian/Farsi locale module
# locales/fa/messages.py
ABOUT_IRONPYTHON_VER = 'IronPython {}.{}.{} در حال اجرا روی'
```
And then in scripts:
```python
# stringlib automatically maps to the correct locale set by user in pyRevit settings
from pyrevit import stringlib
print(stringlib.ABOUT_IRONPYTHON_VER )
```

If user sets the locale to `English (en)` or `Persian/Farsi (fa)` in pyRevit settings, the printed results would be different.

**Required Work/Pros vs Cons:**
- [ ] In all scripts containing user-facing strings,  `from pyrevit import stringlib` needs to be added 
- [ ] All user facing strings in existing code need to be replaced with references to `stringlib`
- [ ] Translators need to watch the changes to the locales module and add required translations. The stringlib module will be design to default to `English (en)` if a string value is missing in current active locale file.
- [ ] Editing the string libraries are easy since they're just normal python files.
- [ ] This method requires less context switch. All strings will be loaded to memory upon locale selection.

**Comment by gtalarico** [comment]
I have used the gettext approach in localised web projects and it was quite nice once it was implemented, but as you already described, setting up the toolchain will be more upfront work.

I think that would still be my preference still be my preference since it will be more maintainable

**Comment by eirannejad** [comment]
@gtalarico I really like `gettext` since the original text is always visible in the main code. I've already tested it and it works under IronPython+pyRevit so I'm gonna take that route.

**Comment by eirannejad** [comment]
- [ ] Look into TextBlob https://textblob.readthedocs.io/en/dev/

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year.
Thanks for pointing it out.
If you feel it is still relevant, feel free to reopen the issue
