### ISSUE TITLE
Batch Import Pat Files always MM

### ISSUE THREAD

**Issue by ponmy** [eirannejad/pyRevit#378]
Patterns loaded via the tool are always set to MM units.  Even when ";%UNITS=INCH" is defined in the pat file.

**Comment by ponmy** [comment]
Sure.  See attached.  Github wouldn't upload a .pat so I switched it to .txt.

[Test.pdf](https://github.com/eirannejad/pyRevit/files/2408320/Test.pdf)

[Test.txt](https://github.com/eirannejad/pyRevit/files/2408321/Test.txt)

**Comment by eirannejad** [comment]
Okay awesome thank! Resolved. Please see below and test again.
The issue was related to setting unit parameter as global. I assumed all parameters are going to be defined after the pattern name.

So now the tool supports both global and local parameter settings. Define the parameters before the pattern names to set them globally for all patterns in that file:
```
;%VERSION=3.0
;%UNITS=INCH
;%TYPE=MODEL
*Block 8x16,  8 x 16 blocks running bond
0,0,0,0,8
90,0,0,8,8,8,-8
```
In this example, the pattern `*Block 8x16` will be version 3.0, INCH, and MODEL since these are set globaly.

However if any parameter is defined locally for a pattern, it will override the global setting. Pattern in example below in the same file will be DRAFTING although global setting is MODEL.
```
*Block2 8x16,  8 x 16 blocks running bond
;%TYPE=DRAFTING
0,0,0,0,8
90,0,0,8,8,8,-8
```
