### ISSUE TITLE
use designscript in pyrevit code

### ISSUE THREAD

**Issue by epeter-** [eirannejad/pyRevit#385]
is there a way to use dynamo methods within pyrevit?
i was trying to implement "myDynamoSolid =myRevitSolid.ToProtoType()"
and was failing with an exception:
"The object reference was not set to an object instance"

why that: designscript offers some nice methods not available in RevitAPI like:
intersectioncurves = myDynamoSolid1.Intersect(myDynamoSolid2)

tx

**Comment by epeter-** [comment]
Ehsan, i cut it down to following code snippet, and actually i am wondering what is causing the exception. if run with Dynamo in background active, the code executes as expected. from pyrevit with no Dynamo in background it fails. so my first question 
**why does Dynamo running in background affect pyrevit execution?**
here my code:
```
# coding: utf8

import clr

clr.AddReference('RevitAPI') 
clr.AddReference('RevitAPIUI') 
clr.AddReference('RevitNodes')

import Revit
from Autodesk.Revit.DB import FilteredElementCollector, BuiltInCategory, IntersectionResultArray, \
		SetComparisonResult, Options, ViewDetailLevel

clr.ImportExtensions(Revit.GeometryConversion)

doc = __revit__.ActiveUIDocument.Document

def collectWalls():
	curview = doc.ActiveView
	cl = FilteredElementCollector(doc, curview.Id)
	stdwalls = cl.OfCategory( BuiltInCategory.OST_Walls ).WhereElementIsNotElementType().ToElements()
	return(stdwalls)

walls = collectWalls()
options = Options()
options.DetailLevel= ViewDetailLevel.Fine

for wall in walls:
	wallSolid = list(wall.get_Geometry(options))[0]
	print wallSolid # for debug shall show Solids
	dynamoSolid = wallSolid.ToProtoType()
```

**Comment by eirannejad** [comment]
Is this the error you're getting?

![pgerror2](https://user-images.githubusercontent.com/8197916/46814004-ab3da880-cd2c-11e8-8944-42a660a927f4.png)

**Comment by epeter-** [comment]
Yes, except the first line that is a debug message to know if I am handling a valid solid

**Comment by eirannejad** [comment]
@epeter- Hey I looked into this a couple of times but didn't have much time or design-script experience to understand the dll dependency with Dynamo Core vs Dynamo Revit RevitNode.dll. This is definitely a DLL reference and loading issue. You need to figure out which DLLs is dynamo loading to make the extensions available in Revit.GeometryConversions. I tried multiple dlls and seems like every time something is missing or more than one `ToProtoType` extension method is available.

Since this is not a conflict or a pyRevit issue I'm gonna close it. Please post a solution if you ever found one. Thanks!

**Comment by htlcnn** [comment]
@eirannejad @epeter- 
I really want to solve this issue to manipulate Dynamo's geometry functions.

I've looked into some code in DynamoRevit project and found these lines:
https://github.com/DynamoDS/DynamoRevit/blob/master/src/DynamoRevit/DynamoRevit.cs#L477-L492
```csharp
        internal static Version PreloadAsmFromRevit()
        {
            var asmLocation = AppDomain.CurrentDomain.BaseDirectory;
            Version libGVersion = findRevitASMVersion(asmLocation);
            var dynCorePath = DynamoRevitApp.DynamoCorePath;
            // Get the corresponding libG preloader location for the target ASM loading version.
            // If there is exact match preloader version to the target ASM version, use it, 
            // otherwise use the closest below.
            var preloaderLocation = DynamoShapeManager.Utilities.GetLibGPreloaderLocation(libGVersion, dynCorePath);

            // [Tech Debt] (Will refactor the code later)
            // The LibG version maybe different in Dynamo and Revit, using the one which is in Dynamo.
            Version preLoadLibGVersion = PreloadLibGVersion(preloaderLocation);
            DynamoShapeManager.Utilities.PreloadAsmFromPath(preloaderLocation, asmLocation);
            return preLoadLibGVersion;
        }
```
In this method, DynamoRevit tries to load **LibG** from Dynamo install folder (on my PC: *C:\Program Files\Dynamo\Dynamo Core\1.3*) depends on which version of Revit is installed.

For Revit 2018, installed version **223A** is detected by the file **C:\Program Files\Autodesk\Revit 2018\ASMAHL223A.dll**: https://github.com/DynamoDS/Dynamo/blob/master/src/Tools/DynamoShapeManager/Utilities.cs#L455-L465
```csharp
        public static Version GetVersionFromPath(string asmPath, string searchPattern = "ASMAHL*.dll")
        {
            var ASMFilePath = Directory.GetFiles(asmPath, searchPattern, SearchOption.TopDirectoryOnly).FirstOrDefault();
            if (ASMFilePath != null && File.Exists(ASMFilePath))
            {
                var asmVersion = FileVersionInfo.GetVersionInfo(ASMFilePath);
                var libGversion = new Version(asmVersion.FileMajorPart, asmVersion.FileMinorPart, asmVersion.FileBuildPart);
                return libGversion;
            }
            throw new FileNotFoundException("$Could not find geometry library binaries at : {geometryLibraryPath}");
        }
```

However, in Dynamo folder there are only 220, 221, 222, 223, 224 of libg folders. I'm wondering how they could load this LibG assembly.

One more thing to notice: in Revit 2018 installation folder, there's only libg_220 folder. I've used dotpeek to view **LibG.ProtoInterface.dll** in that folder and noticed it still had **TSplineSurfaceBuildPipes** method implemented. I wonder which version of LibG.ProtoInterface was referenced when calling ProtoGeometry from pyRevit so that it says 
```
NotImplementedError: Method 'TSplineSurfaceBuildPipes' in type 'Autodesk.LibG.GeometryFactory' from assembly 'LibG.ProtoInterface, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Sorry for my poor C# reading skill, but I hope this finding will help solving the issue
Cheers.

**Comment by artmklgnv** [comment]
@eirannejad 
Hi. I found a solution to this problem. Unfortunately, there is only one way to solve this problem. You need to run dynamo in background. You can easily see this if you run Dynamo player and run your script from toolbar. Ehsan can you make that pyRevit run Dynamo in background?(It can be optional tool in settings). A lot of scripts use Dynamo libraries. It would be useful for many people.

**Comment by epeter-** [comment]
this was already known, respectively the reason for raising the topic ;-)

**Comment by artmklgnv** [comment]
Oh, not carefully read your post =/. But if a solution exists, why not solve it? Loading DLL does not solve the problem. Problem still exist. @epeter-

**Comment by eirannejad** [comment]
@artmklgnv What do you mean by running Dynamo in the background? Running dynamo is quite complex since it can have multiple versions and the user needs to pick the correct version using the Dynamo's internal version picker.

**Comment by epeter-** [comment]
if you run dynamo and pyrevit in parallel all *dynamo* api calls are 
available for pyrevit not only the revit api calls.

asfaik dynamo dlls are not loadable in pyrevit scripts directly

so the workaround is to first start dynamo and then execute your pyrevit 
script

peter

**Comment by artmklgnv** [comment]
@eirannejad I know that DYNO 0.9(similar addon) run dynamo core when Revit start. And all pyRevit script works good with it. I do not know how they run a core, but this is an existing solution at the moment. If you could implement this, it would be very nice.

**Comment by htlcnn** [comment]
Dyno makes a ribbon button and runs dynamo scripts, just like you have
pyRevit's Dynamo bundle with .dyn script inside. That's not similar to
adding reference to ProtoGeometry when you're in a IronPython bundle

**Comment by htlcnn** [comment]
Hi all,
I think I've found a way to use Dynamo Geometry inside pyRevit.
Here's how I did:

**Case 1**. You use `ProtoGeometry` (`Autodesk.DesignScript.Geometry` namespace) only:

```python
import clr
clr.AddReference("DynamoApplications")
from Dynamo.Applications import StartupUtils

def main():
    dynamo_model = StartupUtils.MakeModel(CLImode=True)
    dynamo_model.Start()
    clr.AddReference("ProtoGeometry")
    from Autodesk.DesignScript.Geometry import Point
    try:
        p = Point.ByCoordinates(1, 1, 1)
        print(p)
    finally:
        dynamo_model.ShutDown(shutdownHost=True)
```
Here's output:
![image](https://user-images.githubusercontent.com/931924/75628709-39f6e200-5c0e-11ea-923c-9f334e8bbdf3.png)

---

**Case 2**: You want to convert from Revit Geometry to Proto Geometry and vice versa (using `Revit.GeometryConversion` from `RevitNodes`)

```python
import clr
clr.AddReference("DynamoApplications")
from Dynamo.Applications import StartupUtils


def main():
    dynamo_model = StartupUtils.MakeModel(CLImode=True)
    dynamo_model.Start()
    clr.AddReference("RevitNodes")
    import Revit
    clr.ImportExtensions(Revit.GeometryConversion)
    clr.AddReference("RevitServices")
    from RevitServices.Persistence import DocumentManager
    from Autodesk.Revit.DB import XYZ
    from pyrevit import revit
    try:
        # this line is important because converting geometry needs a reference of
        # DocumentManager.Instance.CurrentUIDocument, which is None if we don't set it
        # to current uidoc (luckily, they leave it public get/set)
        DocumentManager.Instance.CurrentUIDocument = revit.uidoc
        revit_point = XYZ(1, 1, 1)
        dynamo_point = revit_point.ToPoint()
        print('Revit Point: {}'.format(revit_point))
        print('Dynamo Point: {}'.format(dynamo_point))
```
Here's output:
![image](https://user-images.githubusercontent.com/931924/75628751-a5d94a80-5c0e-11ea-8327-677aee8197e0.png)

I think I would make it a decorator in my `lib` so that I can use it whenever I need.
Cheers!

**Comment by eirannejad** [comment]
Hey @htlcnn Can I put this on the Wiki?

**Comment by htlcnn** [comment]
@eirannejad Sure.

**Comment by htlcnn** [comment]
Making a decorator didn't work for me. I had to keep my code logic inside 1 script file. Not sure why, but I'm happy it worked anyway.
If anyone has Exception about ProtoGeometry, please restart Revit and try again.

**Comment by LvironeGreisch** [comment]
Hello,

Does someone know how make this run in a custom C# addin ?

Thanks
