### ISSUE TITLE
Old way to install pyRevit

### ISSUE THREAD

**Issue by chinh-trieutien** [eirannejad/pyRevit#440]
### Issue Description

Could you put the old way installer side-by-side with the new one and we can use that instead.

**Comment by eirannejad** [comment]
What's in the old installer that makes you want it back?

**Comment by chinh-trieutien** [comment]
Hi eirannejad,

I would like to have the "**_install_addin.bat_**" file back to install pyRevit manually cause:

* I don't have administration right
* I would like to install as repository and have manual update by **_pull_**
* I can revert back to older version if i want with **_rebase_** local repository

Thank you, this would help a lot

**Comment by joseph-kirkpatrick** [comment]
[pyRevit Failed Instal Log v4.6.8.txt](https://github.com/eirannejad/pyRevit/files/2624794/pyRevit.Failed.Instal.Log.v4.6.8.txt)
Hello,

I'm having the same issue as chinh-trieutien, cloning the repository and installing that way seemed to work seemlessly for me and my other coworkers before. I have attached my Log from when I tried to install it, and it prematurely ended.

Thanks for your time.

**Comment by eirannejad** [comment]
Hey guys,
We moved away from the old installer due to git install complexities. Please watch the video below for pyRevit's new distribution model:
https://www.youtube.com/watch?v=VZdgrh_US68&t=3s

Also watch this for a demo on the CLI tool:
https://www.youtube.com/watch?v=PMc02W-oAo4&t=24s

The CLI tool has had changes since the video was published so make sure to read the documentation here:
https://github.com/eirannejad/pyRevitLabs/blob/master/README_CLI.md

I'm closing this. Please open another issue if you see bugs with the CLI tool.
