### ISSUE TITLE
Run C# Code on every execution

### ISSUE THREAD

**Issue by eirannejad** [eirannejad/pyRevit#450]
### Issue Description

Currently .cs files in pyRevit bundles are compiled on the fly at load time. Improve the executor to run the .cs files just like a script on every button click. 

RE Improvement ideas on Issue #143  by https://github.com/andrewberes

**Comment by ariccb** [comment]
I previously had this working using a script originally made by Ali Tehami, but it stopped working one day and is giving me a "Error compiling .NET script". It's looking for a file or assembly in my \appdata\local\Temp folder, to a .dll file named after the pyrevit pushbutton like: <pushbuttonname>_<######>.dll

Is this something that is broken in Pyrevit or something that's wrong with my end of the configuration?

**Comment by eirannejad** [comment]
The error prompt should have a drop down showing more info about the error. Does it include anything?

**Comment by ariccb** [comment]
Here is the full error - 
![image](https://user-images.githubusercontent.com/48956351/69386627-6e0e4e80-0c80-11ea-80f7-636e183664ff.png)

**Comment by eirannejad** [comment]
Seems like there is a missing dependency.

The .NET execution system has changed quite dramatically under 4.7. The C# scripts are now compiled on the fly when running the command. See pages below

https://www.notion.so/pyrevitlabs/Create-Your-First-NET-Command-edce7dea66604c3ab059e73425a647c6

https://www.notion.so/pyrevitlabs/Anatomy-of-NET-C-VB-Scripts-1e1667f172fc4e9190eb5fa4c4687707

**Comment by ariccb** [comment]
I tried to add the dependency mentioned in those links: "using PyRevitLabs.PyRevit.Runtime;" but i can't find the .dll file in your pyrevit repository. 

![image](https://user-images.githubusercontent.com/48956351/70647547-677f5100-1c06-11ea-8045-62191add0fed.png)

Just so I understand i'm trying to do this correctly, could you clarify? When trying to use c# scripts within PyRevit, am i copying in the .cs file or the .dll file for it to read from? If my c# script references other c# scripts to use their classes, what do i need to add to my code so that PyRevit can use them?

**Comment by michaelmontagne** [comment]
I'm having this same issue but I'm unsure what the solution was.  Of course, I thought the issue was with my code so I tried pasting the example code and the same error occurred.
