### ISSUE TITLE
Ability to put buttons to Tabs existing on Ribbon 

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#492]
Hey Ehsan! 
I would like to suggest a possibility to put buttons into Tabs on Revit Ribbon, native ones or created by other Addins.

There are several reasons for that. 

At the moment I have a necessity to append some pyRevit buttons to tab, I am creating with c# written addin. My idea that for target user of these scripts it doesn't matter how it was written - with python, dynamo or c#. So it would be more comfortable to have everything developed in a company on one tab.

Another option I can see - sometimes there are not so much scripts to create a certain tab for it. So it could make sense to add these button to Add-ins or Analyse tab.

**Describe the solution you'd like**
I think it would be okay just to append pyRevit buttons at the end of the Tab according to pyRevit extension folders. 

I found an article on TBC https://thebuildingcoder.typepad.com/blog/2013/02/adding-a-button-to-existing-ribbon-panel.html but it seems more like workaround. So I'm not sure if it could be a clean sollution for that.

**Describe alternatives you've considered**
In case of in-house developed addins, maybe it make sense to edit c# written addin, to wait until pyRevit loaded. Or is there are possibilities to create button which linked to c# command with pyRevit?

**Additional context**
Now if I use tab folder name (`Berechnung.tab`) the same as already existing ribbon Tab on pyRevit load there is an error (Berechnung = Analyze in German):
```ERROR: [pyrevit.loader.uimaker] UI error: Can not de/activate native item: Name: Berechnung RevitAPIObject: <UIFramework.RvtRibbonTab object at 0x0000000000000AB3 [UIFramework.RvtRibbonTab]>```

Debug output: https://gist.github.com/melnikovalex/269e0a6e12a1f926977d4fc945756671

Thank you!

**Comment by eirannejad** [comment]
@melnikovalex I understand your point about adding buttons to existing tabs but that's generally bad practice. Addons control the behavior of their tabs so it is best to stay away from mixing tools and commands withing other panels and tabs.

pyRevit provides the **Minify** tool that helps you de-clutter the gui by hiding the extra tabs.

As for using C# with pyRevit, look at [this pyRevit test tool](https://github.com/eirannejad/pyRevit/tree/master/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Unit%20Tests.pulldown/Test%20C%23%20Script.pushbutton). It shows how to create a button with a `script.cs` file that is a C# script. pyRevit compiles this on the fly. It should be limited to simple commands tho with no custom dll references.

**Comment by onomou** [comment]
As @eirannejad said, it's generally a bad practice, but you can use `AdWindows.dll` to move buttons around with the interface. I have been experimenting with inserting existing buttons into other tabs. Here's an example that puts the pyRevit Settings button on the View tab. You should be able to copy-paste into RevitPythonShell, so it also should work with little modification in pyRevit.

```python
clr.AddReference('AdWindows')
import Autodesk.Windows as adWin
ribbon = adWin.ComponentManager.Ribbon
pyRevit_tab = next((x for x in ribbon.Tabs if x.Title == 'pyRevit'))
pyRevit_panel = next((x for x in pyRevit_tab.Panels if x.Source.Name == 'pyRevit'))
settings_button = next((x for x in pyRevit_panel.Source.Items if getattr(x, 'Text', None) == 'Settings'))

target_tab_name = 'View' # change the name here to use a different tab
target_tab = next((x for x in ribbon.Tabs if x.Title == target_tab_name and x.IsVisible)) # Revit sometimes hides other tabs with the same name
target_tab.Panels.Add(adWin.RibbonPanel())

silly_panel = [x for x in target_tab.Panels][-1] # last one in Panels should be the newly created panel
silly_panel.Source = adWin.RibbonPanelSource()
silly_panel.Source.Name = 'Silly Panel'  # not sure which of these
silly_panel.Source.Title = 'Silly Panel' #  is the right attribute to use
silly_panel.Source.Items.Add(settings_button.Clone()) # .Clone() is useful if you want to change the text on just this new button
silly_panel.IsEnabled = True
silly_panel.IsVisible = True

new_button = [x for x in silly_panel.Source.Items][-1] # last one in Items should be the newly created button
new_button.Text = 'pyRevit Settings\nFrom ' + target_tab_name + '!'
new_button.IsEnabled = True
new_button.IsVisible = True
```

[This comment](http://disq.us/p/1nf5r8w) on Jeremy Tammik's blog suggests there may be problems with doing this. So far I have not had any trouble with this approach; I am working toward using it to collect buttons from other places that I use regularly on my custom tab.

Personally, I would love to see pyRevit support (experimentally, since AdWindows is not officially supported by Autodesk, with all the proper disclaimers) creating an extension with a Revit built-in tab name that would then drop your buttons in the right place. Short of that, one should be able to put code like above in an extension startup script.
