### ISSUE TITLE
Clones Deleted by Revit when opening

### ISSUE THREAD

**Issue by michaelmontagne** [eirannejad/pyRevit#497]
I installed pyrevit with these lines:

1. pyrevit config "I:\RAC Opsis\ _pyrevit\pyRevit_config_staff.ini"
2. pyrevit configs seed
3. pyrevit clone opsis base --dest="c:\pyRevit" --debug
4. pyrevit attach opsis 277 --installed --debug

Running 'pyrevit clones' and 'pyrevit attached' show just what I would expect.
After starting Revit, the clones are deleted form the .ini file in appdata. I tried to install in appdata\roaming also and had the same issue.

**To Reproduce**
1. After installation.  open Revit.
2. Settings changes can then not be saved and an error "Error determing current attached clone" appears.
3. A check in the ini file shows no clones listed.
4. pyrevit clones shows no clones
5. pyrevit attached shows no clones attached.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - pyRevit Version 0.3.0 and 4.6.13
 - pyRevit Environment: see attached

[pyenv.txt](https://github.com/eirannejad/pyRevit/files/2805400/pyenv.txt)

**Comment by eirannejad** [comment]
The problem is the order of commands:
1) you're creating the config file and seeding the config file into `%programdata%`
2) The you clone pyRevit, This will update the config file inside `%appdata%/pyRevit` with the new clones
3) You start Revit. pyRevit pulls the seeded configuration and overwrites the config file already in `%appdata%/pyRevit`. This behaviour is intentional so users don't make changes to their pyRevit configurations and the config is always being pulled from the seeded config,

Seed your configs after cloning pyRevit

```shell
pyrevit clone opsis base --dest="c:\pyRevit"
pyrevit attach opsis 277 --installed
pyrevit config "I:\RAC Opsis\_pyrevit\pyRevit_config_staff.ini"
pyrevit configs seed
```

**Comment by michaelmontagne** [comment]
So pyrevit overwrites the appdata version with the seed file (programdata) every time Revit starts?  This explains the blanking of the clones because I didn’t have any clones in my original file that generated the seed.  Fixed that and the value remains now.  Nice.  “pyrevit clones” still returns no clones after a startup of revit.  Where does that info come from?  Because the appdata ini file still shows clones.
There is also the error when trying to save settings from within revit that says “error determining current attached clone”.


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by michaelmontagne** [comment]
The odd thing is that I still have the test installation that works perfectly.  I used the same wrong sequence (probably).  The big difference with that machine is that the user is an admin.
I logged in as a normal user and did a new pyrevit install.  The seed file already existed in programdata from the admin user.  The install went well but when I started Revit, the clones were stripped from the appdata ini file.
Can this be permissions related?


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by eirannejad** [comment]
No. pyrevit puts the configuration in `%appdata%`. pyrevit seed then pushes it to `%programdata%`
Your admin user is used to create this configuration in the first place. So when the admin user runs pyRevit, it does't have to pull from the seeded config file because there is one already in the `%appdata%`

Other users however don't have a config file in `%appdata%`. So when launching pyRevit, they pull from the seeded config.

**Comment by eirannejad** [comment]
Tested and don't see any issues with this. everything works as expected.

**Comment by michaelmontagne** [comment]
Thanks.  Must be something unique to my system.  Just did a new install this morning and it worked fine.


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by eirannejad** [comment]
Ya try to use the latest cli. i have also built an update check into the new versions so it notifies you about available updates
