### ISSUE TITLE
Dynamo conflict here again?

### ISSUE THREAD

**Issue by melnikovalex** [eirannejad/pyRevit#525]
**Describe the bug**
Hey Ehsan. Shortly - when I open Dynamo script there are no wires between nodes, some of the nodes are disappearing. There is an error in Dynamo console:
```This graph has a nodeview with id:2d0d810a-6489-46ab-8686-a86bb1755f6d and name:Watch, but does not contain a matching nodeModel```

After deleting pyRevit.addin - it works correctly again

I found a thread about this issue on Dynamo forum https://forum.dynamobim.com/t/nodes-dissapear-after-reopening-file/30954
I hope it could help and the problem is not so big.

I will try to reproduce it in another environment later and let you know

Thank you!

**To Reproduce**
1. With installed pyRevit run Dynamo
2. Create a new layout with couple of connected nodes (it seems like the problem is only with nodes from packages). While you're creating it some nodes are also not working.
3. Close Dynamo and open again, load the script - there will be no wires more, some of the nodes disappeared
4. Restart Revit without pyRevit, open the script in Dynamo - it is okay again

**Screenshots**
Dynamo sample while creating (it doesnt works, there is null in Watch)
![image](https://user-images.githubusercontent.com/1159403/52795524-3aa7ef00-3072-11e9-8db5-1ae929012559.png)

And after reopening the same file looks like this
![image](https://user-images.githubusercontent.com/1159403/52796524-4694b080-3074-11e9-943b-b8ff2b9394c2.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro (German)
 - pyRevit Version 4.6.15
 - Dynamo Version 2.0.1
 - pyRevit Environment: 

```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.6.15" | Path: "C:
\Users\alex\AppData\Roaming\pyRevit-Master"
==> Attachments
Autodesk Revit 2018.3.1 | Clone: "master" | Engine: "273"
==> Installed UI Extensions
==> Installed Library Extensions
==> Default Extension Search Path
C:\Users\alex\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Language: 1033 | Path: "C:\Program
 Files\Autodesk\Revit 2018\"
==> Running Revit Instances
PID: 4940 | Autodesk Revit 2018.3.1 | Version: 18.3.1.2 | Language: 0 | Path: "C
:\Program Files\Autodesk\Revit 2018"
==> User Environment
Microsoft Windows 8.1 [Version 6.3.9600]
Executing User: NETWORK\alex
Active User: NETWORK\alex
Adming Access: No
%APPDATA%: "C:\Users\alex\AppData\Roaming"
Latest Installed .Net Framework: "4.7.2"
No .Net Target Packs are installed.
pyRevit CLI 0.9.0.0
```

**Comment by eirannejad** [comment]
Thanks @melnikovalex for sharing this issue and the link to the very interesting thread on dynamo forum. Yes these issues are caused by different dll versions used by the addons. I [responded to the thread ](https://forum.dynamobim.com/t/nodes-dissapear-after-reopening-file/30954/10?u=eirannejad) there and will take a look on my side to see if I can improve things.

**Comment by melnikovalex** [comment]
Just tested on another machine - the same problem :(

**Comment by eirannejad** [comment]
It's going to be the same everywhere. This is not a pyRevit issue.
**However:**
You can delete the `pyRevit/bin/NewtonSoft.Json.dll` or replace it with `C:/Program Files/Autodesk/Revit 201X/NewtonSoft.Json.dll` and pyRevit still works fine.

This should solve the problem

**Comment by melnikovalex** [comment]
> **However:**
> You can delete the `pyRevit/bin/NewtonSoft.Json.dll` or replace it with `C:/Program Files/Autodesk/Revit 201X/NewtonSoft.Json.dll` and pyRevit still works fine.
> 
> This should solve the problem

For some reason that did not help. I've tried to replace it with version 8 (from Dynamo), 9 (from Revit) and to delete it. Could it be cached somehow?

**Comment by eirannejad** [comment]
Interesting. Maybe another addon is loading this as well. Open Revit with pyRevit and run `Spy > List Loaded Assemblies` and let it finish listing all assemblies. Then run a search for `NewtonSoft` and find all loaded versions and see where they're loaded from.

**Comment by melnikovalex** [comment]
Without any changes in `pyRevit\bin` (version 12.0.1 is still there) it loads this one: `Newtonsoft.Json 9.0.0.0 C:\Program Files\Autodesk\Revit 2018\Newtonsoft.Json.dll`

**Comment by eirannejad** [comment]
So pyRevit is loading and only one ``Newtonsoft.Json` is loaded??? Then why is Dynamo breaking?

**Comment by melnikovalex** [comment]
That is the question  -maybe some other dlls cause the conflict? I will try to test what else could it be

**Comment by eirannejad** [comment]
@melnikovalex I'd start by verifying there is only one version of `Newtonsoft.Json` is loaded. Generally if pyRevit is loaded, you should see two different versions on the `Spy > List Loaded Assemblies` report.

**Comment by melnikovalex** [comment]
> @melnikovalex I'd start by verifying there is only one version of `Newtonsoft.Json` is loaded. Generally if pyRevit is loaded, you should see two different versions on the `Spy > List Loaded Assemblies` report.

I've checked one more time on a newly created VM with Revit 2019 default installtion (with eTransmit, Model Review, Batch Print, Collaboration and Dynamo 1.3 (?) ). So for me it is only Newtonsoft.JSON.dll v.9.0.0.0 from Revit folder

**Comment by eirannejad** [comment]
@melnikovalex I know there is only one in Revit folder. "Loaded" assemblies matter. Would you mind sending me a the full report from `Spy > List Loaded Assemblies` tool?

**Comment by melnikovalex** [comment]
Here you go: https://gist.github.com/melnikovalex/eb7589d7c71020485af02a10b0eabcef
Interesting - I couldn't reproduce the issue on empty installation of 2019. Either because of empty Revit or because of 2019 version.

**Comment by eirannejad** [comment]
Which pyRevit version are you using. Ya you have definitely only one `Newtonsoft.JSON.dll` loaded. No idea where is the conflict tho.

**Comment by melnikovalex** [comment]
pyRevit 4.6.15
I've tested clean installation of Revit 2018 with the same conditions - the issue is here again

**Comment by kaiaurelienzhu** [comment]
@melnikovalex 

There is also another thread for this on the DynamoBIM github. So far, issue has not yet been resolved.Here is the link for your reference.

https://github.com/DynamoDS/Dynamo/issues/9497

**Comment by eirannejad** [comment]
Well what I'm not fully understanding and trying to figure out is that if pyRevit's `Newtonsoft.JSON.dll` is not loaded, then what's causing the conflict. It might be another dll.

**Comment by eirannejad** [comment]
Hmm mine has a completely different issue

![2019-02-26 16_27_07-](https://user-images.githubusercontent.com/8197916/53456469-6a94b200-39e3-11e9-936f-ec00e34c05c7.png)

**Comment by eirannejad** [comment]
Hmm I'm confused. See for yourself

Loaded assemblies - No pyRevit - Before Dynamo load
[before.txt](https://github.com/eirannejad/pyRevit/files/2908205/before.txt)

Loaded assemblies - No pyRevit - After Dynamo load
[after.txt](https://github.com/eirannejad/pyRevit/files/2908213/after.txt)

Loaded assemblies - with pyRevit - Before Dynamo load and running any pyRevit commands
[py-before.txt](https://github.com/eirannejad/pyRevit/files/2908214/py-before.txt)

Loaded assemblies - with pyRevit - After running a few pyRevit commands
[py-after.txt](https://github.com/eirannejad/pyRevit/files/2908215/py-after.txt)

Loaded assemblies - with pyRevit - After Dynamo load
**HERE IS THE DYNAMO LOAD ERROR**
[dyn-after-py.txt](https://github.com/eirannejad/pyRevit/files/2908216/dyn-after-py.txt)


Running a diff between **Left:** `after.txt` and **Right:** `dyn-after-py.txt` to see what has been loaded with pyRevit that might be causing the issue. I can't seem to find the root cause.

![2019-02-26 17_43_17-window](https://user-images.githubusercontent.com/8197916/53459427-9b2e1900-39ee-11e9-9e3e-eff15ee12ea7.png)

![2019-02-26 17_43_27-window](https://user-images.githubusercontent.com/8197916/53459431-9d907300-39ee-11e9-868e-3824ae2a5abf.png)

![2019-02-26 17_50_12-window](https://user-images.githubusercontent.com/8197916/53459503-feb84680-39ee-11e9-9684-501fd1a30875.png)

![2019-02-26 17_43_42-window](https://user-images.githubusercontent.com/8197916/53459433-a08b6380-39ee-11e9-8e14-fd551082bb83.png)

**Comment by melnikovalex** [comment]
> Hmm mine has a completely different issue

I had the same alert several times, but I couldn't find any regularity there. It appears sometimes or could not show itself at all (e.g. on VM I haven't seen it).

**Comment by mjkkirschner** [comment]
@eirannejad I have an experiment I would like to try but I have not gotten time yet to do it - it may be faster for you if you have the time/desire.

I see that pyRevit targets .net 4.7.1 - and the problems we see here are in 2018-  not in 2019. I believe though have been unable to confirm that 2018 hosted an older version of the .net framework (unrelated to what version the user has installed on their machine) and so addins are loaded into an older framework version of .net in 2018. - again - unconfirmed. I would like to rebuild pyRevit targeting say  - .net.4.5.2 - and see if the problem is solved in 2018. It may be that multi targeting pyRevit to different versions of .net for different versions of Revit solves this issue.

**Comment by tatlin** [comment]
Hi Ehsan and MikeK,

I have Dynamo 2.0.0 and pyRevit 4.6.x installed and running on Revit 2019.
Both run fine independently but note there still are issues getting these
two to run together in 2019, not just 2018. I get around the conflict by
invoking two instances of Revit now, one for pyRevit and one for Dynamo. I
do not have 2018 installed but can do that if needed.

Do you think the underlying conflict is in Newtonsoft.Json library version
or somewhere else? the linked Dynamo github issue seems inconclusive.

Either way, I can help build and test and isolate. I know how to build
pyRevit now and have built the newest dev versions as well as older
versions Ehsan has created. Happy to help if you can write down the
particular cases we want to test for.

-matt

**Comment by eirannejad** [comment]
@tatlin Any specifics on issues you're seeing on 2019?

**Comment by tatlin** [comment]
after opening Revit 2019.2 and having the vanilla pyRevit addin loaded, when I try to invoke Dynamo 2.0.2 it bombs out in a similar manner discussed in this thread. see attached screenshot. Nothing really shows in the DynamoRevit or DynamoCore Logs. 

![image](https://user-images.githubusercontent.com/1142008/54047884-446ecf00-41a6-11e9-9a9e-71e1e0dd5266.png)

**Comment by eirannejad** [comment]
Okay. See issue #538. This is most probably related. I'm working on making the pyRevit binder smart about responding to bindings for its own dlls only. Will keep you posted. I have a hunch this is the root cause.

**Comment by eirannejad** [comment]
Confirmed the pyRevit internal binding resolver was the root cause. Making it only respond to requests coming from pyRevit assemblies resolved both #535 and issues listed on this thread.

The commit about is for 4.7 on develop branch. I'll back port this change to 4.6 and will publish with 4.6.18

**Comment by eirannejad** [comment]
@tatlin Hey Matt. You can switch to `release/4.6.18` now, build the Labs solution and run tests.

**Comment by tatlin** [comment]
Will try later tonight.

**Comment by eirannejad** [comment]
Per user feedback this issue seems to be resolved for now.

**Comment by eirannejad** [comment]
Re #578 
Recompiled Newtonsoft.Json (12.0.1) recompile to pyRevitLabs.Json (.NET 4.7.1)
This removes the conflict between pyRevit and other addons using a different version of Newtonsoft.Json

**Comment by eirannejad** [comment]
@tatlin Seems like the `TextBox.ISReadOnly` conflict with Dynamo is a [framwork bug](https://stackoverflow.com/questions/6850713/weird-xaml-parsing-error-when-trying-to-set-textbox-isreadonly--)

Resoolved here: https://github.com/eirannejad/pyRevit/commit/ee7b74993386219375779c4a45f774c1a23174c0
