### ISSUE TITLE
Place model views in sheets

### ISSUE THREAD

**Issue by ckopietz** [eirannejad/pyRevit#567]
Hi there,

Is there a way that I can select a batch of views and place automatically in the sheet using pyrevit?

would be lovely to have something like that in the plugin to save time of placing manually.

Many thanks
CK

**Comment by Robbo1234** [comment]
FYI CK
![image](https://user-images.githubusercontent.com/8776947/55473214-04183a80-5606-11e9-83d1-680c98edb01d.png)

**Comment by ckopietz** [comment]
Thank you so much!

Cheers
CK

**Comment by Teflon98** [comment]
This is fantastic!

Is there a way to automatically distribute them instead of having them stack on top of one another?

I don't expect it to auto-fill, but it would great if the were at least aligned in some grid pattern.

Perhaps a third dialog box indicating origin of grid and the number of columns and rows?

Just a wish.

Thank you again!

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year.
Thanks for pointing it out.
If you feel it is still relevant, feel free to reopen the issue
