### ISSUE TITLE
Renaming Object Styles (line styles) inside a family

### ISSUE THREAD

**Issue by DanGarnier** [eirannejad/pyRevit#587]
{ } ReValue Command
I tried using the ReValue Command to rename all the object styles (line styles) inside a family. But I noticed I have to have the lines selected and it will only change those styles. There are other styles that also need to be renamed within the family.

Solution:
It would be great if I could grab all the object styles (line styles) inside a drafting family and change the name.

![Annotation 2019-05-02 100732](https://user-images.githubusercontent.com/50120788/57081132-23b48880-6cc2-11e9-8354-bf17f6f30df4.gif)

Thank you!!
Dan

**Comment by eirannejad** [comment]
There are not "Line Styles" inside a family. There are "Graphic Styles" (object styles) that could be assigned to lines (detail or model) and other solid elements inside the family. Revit interface doesn't let you 'select' these items and a selection is required for the ReValue tool.

I have plans to improve this tool so it is easy to select all sorts of Types and Styles around the Revit model. At the moment even if you select these graphic styles, the tool can not rename them since the renaming mechanism is different than other elements. I'll make a note of fixing this.

- [ ] Make ReValue smart about changing all types of parameters on all categories.

I'd like to point out two tools that might come handy in the future with similar issues:

- `pyRevit > Selection > Select > Select Element Types` list all element types in a model and provides an easy interface to 'select' those.

- `pyRevit > pyRevit > Spy > List Elements` also provides a way to list a series of categories with their element Ids.

Both these tools still need improvements.

I'll keep this open until the task listed above is completed.

**Comment by DanGarnier** [comment]
Thanks for the quick response Ehsan!

Yes, it is the "Graphic Styles" (object styles) that I need to rename
inside the family. I have hundreds of families to rename, so doing it
manually wouldn't be very smart. So, if additionally this task can be
performed without having to open the family then it would be so wonderful.
I realize as I write this that it may be very difficult to do that, but I
guess "if we can dream it we can achieve it"...right?

I hope you are having a great day,
Daniel

**Comment by eirannejad** [comment]
It's actually not that difficult. [Take a look at this](https://www.youtube.com/watch?v=_HldsaHA8i8)

I might be able to help you with the python script that renames the graphic styles inside the families for now, until the pyRevit tools are updated (most probably in v4.7 final)

**Comment by DanGarnier** [comment]
Thanks! Do I understand correctly that the video explains a way to access
different files without opening them? And then additional programming would
be necessary to perform a task (e.g.: renaming "Graphic Styles" inside a
family)?

**Comment by eirannejad** [comment]
Yes pyRevit `run` allows batch executing a python script over a series of revit models

**Comment by jmcouffin** [comment]
**Closing**
Issue older than a year. 
Thanks for pointing it out. 
If you feel it is still relevant, feel free to reopen the issue
