### ISSUE TITLE
Dynamo/pyRevit Not Executing Simple Command

### ISSUE THREAD

**Issue by JAMA-KB1989** [eirannejad/pyRevit#732]
Hello Ehsan,

I have added a formal video / ticket for this issue as hopefully others may of experienced this issue and can aid in helping solve it.  There was a post back in January (https://stackoverflow.com/questions/54268759/launch-a-dynamo-graph-dyn-file-from-python-script)  about the same thing happening.  Not sure what the issue is, but let me know what you want me to provide to help support / fix any Python coding needed.  

Video: https://youtu.be/ZS4WGPJ7KEg 

Thank you again,
Kevin

**Comment by eirannejad** [comment]
Okay. Would you mind sharing a bit of info here to help me replicate the issue

1. Example Revit model and dynamo script that causes the issue
2. Addons installed on Dynamo
3. Dynamo version
4. Run `pyrevit env` in terminal and share results as well

**Comment by JAMA-KB1989** [comment]
Hello Ehsan,

Thank you so much for such a quick prompt.  Please see the results / debug results.  I hope this helps!

The Script is pretty simple and does not really rely on too many Packages but have attached the list we have installed.  The script works no problems with Dynamo open.

Dynamo (Core) Version: 2.1.0.7500
Dynamo (Revit) Version: 2.1.0.7733
(Up to date)

Link To Files: https://www.dropbox.com/sh/34a9ouly5zh0kme/AABHdANUzAfhmjYkRMCFAIYFa?dl=0 

Thank you again Ehsan!
- Kevin

**Comment by eirannejad** [comment]
Okay made a series of improvements that should make dynamo script be executed faster

Dynamo has an option to shutdown the executor after running the dynamo script. This means that scripts take longer to run since it has to load dynamo first (and if dynamo needs to check for updates or do other startup tasks that is also added to the script exec time)

pyRevit previously would request to shutdown by default to avoid memory leaks and conflicts

```csharp
{ "dynModelShutDown", "True"},
```

Now the user can specif (in bundle file) whether to use a clean dynamo engine or keep it in memory so next executions are faster

```yaml
engine:
  clean: false
```
and the revised executor uses this passes thi config to dynamo

```csharp
{ "dynModelShutDown",  ExecEngineConfigs.clean ? "True" : "False" },
```

**Comment by eirannejad** [comment]
Runs a lot faster when `clean: false`

![2019-10-28_16-45-10](https://user-images.githubusercontent.com/8197916/67726220-5950da80-f9a2-11e9-8826-5ad39b3ab86e.gif)

**Comment by JAMA-KB1989** [comment]
Excellent Ehsan!  Any chance I could get the files to double check and/or just know where to modify the python files?

**Comment by XTDHub** [comment]
Still cannot run Scripts with Custom UI

**Comment by jmcouffin** [comment]
> Still cannot run Scripts with Custom UI

Set your .dyn file to run in automatic, you can do it by either opening it in dynamo and set it to Automatic or much more quickly by opening the dyn file in notepad, look for "Manual" and Replace by "Automatic"
