### ISSUE TITLE
Manage Keynote - Add Categories / Keynotes - error

### ISSUE THREAD

**Issue by Mairh93** [eirannejad/pyRevit#759]
Hello,

I am new in pyRevit so maybe I am doing something wrong..When I add Category or Keynote using the Manage Keynote I get the error ' Set property System.Windows.Controls..SpellCheck.Is..threw an exception.', and nothing happens then. 

![Keynote](https://user-images.githubusercontent.com/27021809/69734724-c5ecff80-112f-11ea-9adb-7e9fc04323e8.PNG)

Thank you a lot for your work so far!

**Comment by admiralarcharch** [comment]
I am getting this error also.

**Comment by Siversmith** [comment]
Whenever we have 2 revit's open and I select Pyrevit's tool Keynote manager I get this same error.

Set Property
'System.Windows.Controls.SpellCheck.Is…
threw an exeption.

**To Reproduce**
Steps to reproduce the behavior:
1. Open 2 Revits
2. Click on 'Keynote Manager'
3. See error

**Expected behavior**
I wanted it to open the Keynote manager.

**Screenshots**

![error](https://user-images.githubusercontent.com/59952907/73727482-3a4cac00-473a-11ea-9f03-cb3ba1400b9d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - pyRevit Version 4.7 -beta4
- pyRevit Environment: 
"Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Clinton.Wernars>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.7-beta4" | Path: "C:\Users\Clinton.Wernars\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2020.0.1 Hotfix" | Engine: 277 | Path: "C:\Users\Clinton.Wernars\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Clinton.Wernars\AppData\Roaming\Autodesk\Revit\Addins\2020\pyRevit.addin"
master | Product: "2019.2.2 Hotfix" | Engine: 277 | Path: "C:\Users\Clinton.Wernars\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Clinton.Wernars\AppData\Roaming\Autodesk\Revit\Addins\2019\pyRevit.addin"
master | Product: "2018.3.3 Security Fix" | Engine: 277 | Path: "C:\Users\Clinton.Wernars\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Clinton.Wernars\AppData\Roaming\Autodesk\Revit\Addins\2018\pyRevit.addin"
master | Product: "2017.2.5 Security Fix" | Engine: 277 | Path: "C:\Users\Clinton.Wernars\AppData\Roaming\pyRevit-Master" | Manifest: "C:\Users\Clinton.Wernars\AppData\Roaming\Autodesk\Revit\Addins\2017\pyRevit.addin"
==> Installed Extensions
OSCAR_Extensions | Type: Unknown | Repo: "" | Installed: "C:\Users\Clinton.Wernars\Aurecon Group\Bridge Offshore Team - Documents\Library\120 DYNAMO RESOURSES\02 CODES\PYREVIT BUTTONS\DEPLOYED EXTENSIONS\OSCAR_Extensions.extension"
==> Default Extension Search Path
C:\Users\Clinton.Wernars\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\Clinton.Wernars\Aurecon Group\Bridge Offshore Team - Documents\Library\120 DYNAMO RESOURSES\02 CODES\PYREVIT BUTTONS\DEPLOYED EXTENSIONS
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2020.0.1 Hotfix | Version: 20.0.1.2 | Build: 20190412_1200(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018"
2017.2.5 Security Fix | Version: 17.0.1169.0 | Build: 20190508_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2017"
==> Running Revit Instances
PID: 21184 | 2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> User Environment
Microsoft Windows 10 [Version 10.0.17134]
Executing User: AURECON\Clinton.Wernars
Active User: AURECON\Clinton.Wernars
Admin Access: No
%APPDATA%: "C:\Users\Clinton.Wernars\AppData\Roaming"
Latest Installed .Net Framework: 4.7.2
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI 0.16.0.0""

**Comment by eirannejad** [comment]
Okay thanks for the reports. This has been coming up a lot. I might disable the spellcheck on the text editor to fix the issue. A temporary fix would be to:

- Open the `/extensions/pyRevitTools.extension/pyRevit.tab/Drawing Set.panel/Keynotes.pushbutton/EditRecord.xaml` in the pyRevit installation directory. (You can easily access this by holding ALT and clicking the **Manage Keynotes** button)
- Find the line # 73
- Edit the line by removing the `SpellCheck.IsEnabled="True"` part. Make sure the line is still closed by the `/>`

Lemme know if this fixes the issue

**Comment by stevek44** [comment]
Your fix worked for me. I never had this occur until, it seems, I used the Revit spell check tool on a keynote. Thanks for creating pyRevit. I use it alot.

**Comment by Siversmith** [comment]
Hi eirannejad. I tested out the remove of the spell check and so far it seems to be fine. Will come back to if I notice anything about it still crashing.

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by ahermans3d** [comment]
The above work around for only having one Revit session works for Revit 2019. It does not work with Revit 2020. Do you know when the next update release will be availabe? Thank you for all of your amazing tools :)
