### ISSUE TITLE
Is it possible to have multiple icon states?

### ISSUE THREAD

**Issue by jagostinhoCT** [eirannejad/pyRevit#761]
Thinking about something showing Red, Amber or Green depending on the script run result.
Or, even better, a status that updates automatically based on a hook.

An example
If number of Warnings are above a set value, change tool icon to Amber, or Red. Else, leave it as Green.

I tried to find documentation on how to change icon status. Is this being explained somewhere I can read about?

Thank you,
Joaquim

**Comment by eirannejad** [comment]
Yes you can. The pyRevit `script` module has a `set_icon` method that can set the icong (`.png` file) on the command that is running. Hooks are a bit more complex since they don't have a UI button. You need to find the button on your tab and set the icon. For that look into `pyrevit.coreutils.ribbon` module. Let me know if you need more info
