### ISSUE TITLE
make script.pyc (compiled python files) executable !! 

### ISSUE THREAD

**Issue by tillbaum** [eirannejad/pyRevit#858]
Making compiled python files - script.pyc -  executable would be a nice feature to provide a 
little protection from modifying script.py files through the user. 

Or even better. Make the Cython format *.pyx available.

**Comment by eirannejad** [comment]
Implementing support for `pyc` binaries needs a ready strong implementation of the Cpython over Revit. That's a huge project.

You can compile the IronPython codes however. See the test bundle here:
https://github.com/eirannejad/pyRevit/tree/master/extensions/pyRevitDevTools.extension/pyRevitDev.tab/Debug.panel/Engine%20Tests.pulldown/Test%20IronPython%20Compile.pushbutton

I'm closing this since there is no roadmap for cpython at the moment. Once cpython is implemented, running `pyc` binaries will be a given.
