### ISSUE TITLE
Creating a schedule from CSV

### ISSUE THREAD

**Issue by knwlss** [eirannejad/pyRevit#861]
Trying to create a schedule from CSV. It used to work perfectly fine before (version 4.7.4), but now all I manage to get is an empty schedule. The information from the cells is not imported.

1. Created a schedule in Excel and exported it to CSV.
![image](https://user-images.githubusercontent.com/62601540/77434936-483db580-6dea-11ea-9714-0dfbc1c32ad9.png)
2. Created text project parameters with the same titles.
![image](https://user-images.githubusercontent.com/62601540/77435527-1416c480-6deb-11ea-8d14-e7c4164e1654.png)
3. Used pyRevit tool to create the schedule in the same category and... nothing. The schedule is created, but parameters from the category are not included in the schedule automatically.
![image](https://user-images.githubusercontent.com/62601540/77435293-d1ed8300-6dea-11ea-8d62-fec7547bc5f6.png)
![image](https://user-images.githubusercontent.com/62601540/77435648-3a3c6480-6deb-11ea-9915-f3fdee237c39.png)

I can't wrap my head around this issue - is it a bug or I'm doing something wrong?

**Comment by eirannejad** [comment]
Would you mind sharing the schedule so I can test? I might have broken something.

**Comment by knwlss** [comment]
Sure. Here you go - CSV and RVT files:
https://drive.google.com/file/d/1lRjnHX03zTlPZj8IOD_T8qQDk_qwbvHM/view?usp=sharing
https://drive.google.com/open?id=1E1fSQcIftBnlIunQ8kpAnE1qMkoUhy1u

Also contents of the CSV file:
Data1;Data2;Data3;Data4
A1;A2;A3;A4
B1;B2;B3;B4
C1;C2;C3;C4

**Comment by eirannejad** [comment]
Great! Let me test

**Comment by eirannejad** [comment]
Okay. CSV stands for Comma-Separated-Value meaning that the field values for each record is separated usually by a comma. Your CSV file looks like this:

![Screen Shot 2020-03-27 at 15 55 00](https://user-images.githubusercontent.com/8197916/77806932-6b16d680-7043-11ea-9338-2b54043917e9.png)

The values are separated by `;` so the script basically reads all of the `Data1;Data2;Data3;Data4` string as the first field name as it was expecting `,` as delimiter by design.

I'd like to keep the CSV formatting in pyRevit consistent and always use comma. So It's be great if you can export your CSVs the same way from Revit. Make sure to select comma as delimiter:

![Screen Shot 2020-03-27 at 16 00 56](https://user-images.githubusercontent.com/8197916/77807156-2c355080-7044-11ea-8af6-2eee32bd1937.png)

**Comment by knwlss** [comment]
Amazing! The solution is very simple indeed. Thank you, Ehsan, and many thanks for the great product and its continuous improvement. You are awesome.
