### ISSUE TITLE
pyRevit Import Forms Question

### ISSUE THREAD

**Issue by daveBisMe** [eirannejad/pyRevit#889]
I grabbed some code from a site that used “from pyrevit import forms” to add forms to scripts.  I cannot figure out what I need to do to have this functionality in my scripts.  I’ve looked all through the docs, but what am I missing?  Is it something that goes in a startup script somewhere?

When I type "from pyrevit import forms" in Revit Python Shell I get this error:

ImportError: No module named pyrevit

Side Note: pyRevit is awesome, I'm glad I found it!

**Comment by eirannejad** [comment]
Make sure you have added the path to the `pyrevitlib/` in the RevitPythonShell settings otherwise it won't be able to find pyRevit python module

Take a look at these links on the pyRevit Wiki

https://www.notion.so/Effective-Output-43baf34d2ca247ada8e040bcb86613a2
https://www.notion.so/Effective-Input-ea95e95282a24ba9b154ef88f4f8d056
https://www.notion.so/Visualizing-Data-fd778a0b67354ff581aa340619b87803

**Comment by onomou** [comment]
I posted an answer on #1502 that also applies to this question:

```python
import sys
sys.path.append(r'C:\Users\<username>\AppData\Roaming\pyRevit-Master\pyrevitlib')
sys.path.append(r'C:\Users\<username>\AppData\Roaming\pyRevit-Master\site-packages')
from pyrevit import forms
```

Just replace <username> and paste into RevitPythonShell, provided pyRevit is installed in the default location.
