### ISSUE TITLE
X, Y, Z- coordinates for the family instances

### ISSUE THREAD

**Issue by ankitdarda** [eirannejad/pyRevit#912]
There has been a lack of XY coordinate scheduling in Revit for any of the family instances. I have seen paid plugins where it can create shared parameters and report the family instance X/Y/Z coordinates which can be scheduled and listed for any instance in the project. Can we have similar feature in PyRevit? thanks

**Comment by eirannejad** [comment]
Ya of course. A simple tool can be created but it would require manually clicking on the tool to update the data in the schedules. More complex tools can also be created that would listen to any document change and would update the location parameters, however for that I'd suggest a custom C# addon so you benefit from the increased performance.

I'm gonna close this since it is a question but please continue the discussion
