### ISSUE TITLE
Hi, i am from Russia, my name is Dany, and i have a problem with pyrevit

### ISSUE THREAD

**Issue by daniilkurmelev** [eirannejad/pyRevit#987]
When i open revit 2019? i have this problems.
![Ошибка при установке pyrevit](https://user-images.githubusercontent.com/70519359/91717064-785b6280-eb99-11ea-9ba8-8ae25470a0c7.png)

**Comment by eirannejad** [comment]
Hey Dany,
I'm going to close this issue since you did not provide any of the requested information on the template. Please create a new issue, read the template issue content and provide the requested information. It's very hard for me to figure why this issue is happening on your machine without that info. Thanks

**Comment by zahmadsaleem** [comment]
Those non standard unicode characters in the username might be throwing errors while parsing pyrevit paths?
